// Real corpus lines wrap across adjacent literals; the tables keep each
// corpus line verbatim, one literal per entry.
// ignore_for_file: no_adjacent_strings_in_list, lines_longer_than_80_chars

import 'dart:io';

import 'package:salt_server/src/db/salt_database.dart';
import 'package:salt_server/src/nutrition/engine.dart';
import 'package:salt_server/src/nutrition/matcher.dart';
import 'package:salt_shared/salt_shared.dart';
import 'package:test/test.dart';

import 'support/corpus.dart';
import 'support/fdc_fixtures.dart';

/// Matcher v21: the v21 plan's zero-request rules — rewrites onto answers
/// snapshot 13 already holds (M1), rank-as items reading a cached answer
/// under the record's own words (M2), a water and a non-food word (M3), and
/// the grams rules G1–G6. Every row of [_moved] is a real corpus line the
/// cache-only replay of snapshot 13 moved (the plan's 197 + J5's tapioca
/// starch); FDC answers recorded from snapshot 13
/// (tool/record_fdc_fixtures.dart --from-db), never live.
void main() {
  SaltDatabase tempDb() {
    final dir = Directory.systemTemp.createTempSync('salt-v21');
    addTearDown(() => dir.deleteSync(recursive: true));
    final db = SaltDatabase.open('${dir.path}/salt.db');
    addTearDown(db.dispose);
    return db;
  }

  // A table row's line as its corpus file stores it: the parse of its raw,
  // or the file's own line where the parse differs ("12 (8½-inch) round
  // rice paper wrappers" parses 'round' as the count's unit).
  IngredientLine lineOf(String raw, [IngredientLine? stored]) {
    if (stored != null) {
      return stored;
    }
    final parsed = parseIngredientLine(raw);
    return IngredientLine(raw: raw, item: parsed.item, amounts: parsed.amounts);
  }

  // One line alone, computed on the recorded answers in [db] (a fresh
  // database: nothing cached but what the compute fetches).
  Future<IngredientMatchRow> computeIn(
    SaltDatabase db,
    IngredientLine line,
  ) async {
    db.upsertSource(slug: 'src', name: 'Test', type: 'book');
    final recipe = Recipe(
      id: 'r',
      title: 'r',
      slug: 'r',
      source: const RecipeSource(name: 'Test', type: 'book'),
      ingredients: [
        IngredientGroup(items: [line]),
      ],
    );
    db.upsertRecipe(recipe, sourceSlug: 'src', contentHash: 'hr');
    await matchAndCompute(db, FixtureProvider(), recipe);
    return db.ingredientMatchesFor('r').single;
  }

  Future<IngredientMatchRow> computeLine(IngredientLine line) =>
      computeIn(tempDb(), line);

  MatchBucket bucketOf(IngredientMatchRow row) => matchBucketFor(
    status: row.status,
    fdcId: row.fdcId,
    grams: row.grams,
    confidence: row.confidence,
    hold: row.hold,
    gramSource: row.gramSource,
  );

  test('every moved row derives its item and lands on its record, grams, '
      'bucket and confidence class (the M1 targets and M2 answers rank the named record first; a '
      'macro-incomplete top yields to its same-food twin, as the compute '
      'does: "Salami, hard, sliced" → "Salami, NFS")', () async {
    for (final (
          file,
          _,
          raw,
          item,
          normalized,
          fdcId,
          grams,
          rule,
          bucket,
          passes,
        )
        in _moved) {
      final line = lineOf(raw, item);
      final reason = '$file: $raw ($rule)';
      expect(normalizeItem(lineItemOf(line)), normalized, reason: reason);
      final row = await computeLine(line);
      expect(row.fdcId, fdcId, reason: reason);
      expect(row.grams?.toStringAsFixed(2), grams, reason: reason);
      expect(bucketOf(row).wire, bucket, reason: reason);
      expect(belowConfidenceGate(row.confidence), !passes, reason: reason);
    }
  });

  test('every moved row is a real corpus line at its position, deriving its '
      'item', () {
    for (final (file, position, raw, item, normalized, _, _, _, _, _)
        in _moved) {
      final recipe = loadCorpusRecipe(file);
      final line = nutritionLines(recipe)[position];
      expect(line.raw, raw, reason: file);
      expect(
        normalizeItem(lineItemOf(weighedLine(recipe, line))),
        normalized,
        reason: raw,
      );
      if (item != null) {
        expect(line, item, reason: raw);
      }
    }
  }, skip: skipIfNoCorpus);

  test('J3: the rice-wine rewrite lands ON the review gate — "Wine, rice" '
      'at exactly 0.500, counted (1 tablespoon: 14.64 g)', () async {
    final row = await computeLine(
      lineOf('1 tablespoon Chinese rice wine or dry sherry'),
    );
    expect(row.fdcId, 2710691);
    expect(row.confidence, 0.5);
    expect(belowConfidenceGate(row.confidence), isFalse);
    expect(row.grams?.toStringAsFixed(2), '14.64');
  });

  test('M2: a rank-as item is never a rewrite key or target, so never a '
      'leftAlternative food noun', () {
    for (final key in rankAsKeys) {
      expect(searchQueryFor(key), key, reason: key);
      expect(
        leftAlternative('$key or italian basil leaves', (_) => false),
        isNull,
        reason: key,
      );
    }
  });

  test('M2: no v21 rewrite key is one word — "chianti", "lemongrass" and '
      '"vermicelli" are rank-as, reading their old targets\' answers under '
      'the same words (their table rows land unchanged)', () {
    // Every key, not three names (Run 053 critic): the one-word keys are
    // exactly the ones that predate v21, so a new one-word rewrite key — a
    // leftAlternative food noun, the 'thai' class — fails here.
    expect(queryRewriteKeys.where((k) => !k.contains(' ')).toSet(), const {
      'pepper', 'peppercorns', 'cayenne', 'cointreau', 'amaretto', 'kahlua', //
      'calvados', 'cognac', 'armagnac', 'bourbon', 'scotch', 'whisky',
      'cinnamon', 'bacon', 'shrimp', 'sherry', 'vermouth', 'lager', 'penne',
      'campanelle', 'spaghettini', 'linguine', 'rigatoni', 'orecchiette',
      'farfalle', 'ziti', 'fusilli', 'gemelli', 'cavatappi', 'bucatini',
      'tagliatelle', 'fettuccine', 'pappardelle', 'orzo', 'ditalini',
      'spaghetti', 'turkey', 'chicken', 'short', 'dark', 'dill', 'mint',
      'butter', 'gelatin', 'peas', 'pancetta', 'panko', 'stout', 'tubetti',
      'madeira', 'pepperoncini', 'baguette', 'nutella',
    });
    for (final (key, answer) in const [
      ('chianti', 'red wine'),
      ('lemongrass', 'lemon grass stalks'),
      ('vermicelli', 'pasta dry enriched'),
    ]) {
      expect(rankAsFor(key), (query: answer, answer: answer), reason: key);
    }
  });

  test('M2: lineSearchFor reads a rank-as item first; "Thai or Italian basil '
      'leaves" (1193 line 9) keeps its own search, never the fragment\'s '
      'hot pepper (its landing is still a wrong record in review)', () {
    final db = tempDb();
    expect(lineSearchFor(db, 'thai', 'thai'), (
      query: 'jarred hot cherry peppers',
      answer: 'jarred hot cherry peppers',
    ));
    final basil = lineSearchFor(
      db,
      'thai or italian basil leaves',
      'thai or italian basil leaf',
    );
    expect(basil.query, isNot('jarred hot cherry peppers'));
    expect(basil.answer, isNot('jarred hot cherry peppers'));
  });

  test(
    'G1: the jelly densities are scoped — "¼ cup apricot preserves or hot '
    'pepper jelly" (1191 line 3) keeps its apricot record\'s cup, 80.00 g',
    () async {
      // As in the library, 'apricot preserves' is a cached query, so the
      // line reads A alone ([leftAlternative]).
      final db = tempDb();
      await searchCandidates(db, FixtureProvider(), 'apricot preserves');
      final row = await computeIn(
        db,
        lineOf('¼ cup apricot preserves or hot pepper jelly'),
      );
      expect(row.fdcId, 170645);
      expect(row.grams?.toStringAsFixed(2), '80.00');
      expect(row.gramSource, 'portion');
    },
  );

  test("G2/G3: a bare 'fruit' or own-noun portion up to 350 g sizes the "
      'item; the 625 g "roast" stays capped', () async {
    final db = tempDb();
    final provider = FixtureProvider();
    for (final (raw, fdcId, grams) in const [
      // 0705 line 6: 169910 'fruit without refuse' 336 g.
      ('2 mangos, peeled, pitted, and cut into ½-inch dice', 169910, 672.0),
      // 0287 line 6: 173619 'leg, bone and skin removed' 265 g.
      (
        '4 whole chicken legs, separated into drumsticks and thighs and '
            'skin removed',
        173619,
        1060.0,
      ),
    ]) {
      final food = (await provider.food(fdcId))!;
      expect(lineGrams(db, lineOf(raw), food)?.grams, grams, reason: raw);
    }
    const wellington =
        '1 center-cut beef tenderloin roast, 3 pounds trimmed weight, 12 to '
        '13 inches long and 4 to 4½ inches in diameter';
    final roast = (await provider.food(171748))!;
    expect(roast.portions.map((p) => p.gramWeight), contains(625.0));
    // The 625 g "roast" stays capped; since matcher v37 the line reads the
    // weight it prints in its comma clause (3 pounds).
    expect(lineGrams(db, lineOf(wellington), roast)?.grams, 3 * 453.592);
  });

  test(
    "J2/J5: a stand-in's line says so in its basis — the approximate "
    'densities and the approximation records; a plain density does not',
    () async {
      for (final (raw, basis) in const [
        (
          '2 tablespoons ground dried Aleppo pepper',
          '2 tablespoon ≈ 30 mL · approximate (paprika density)',
        ),
        // Grated Pecorino weighs its own printed figure now (v23 G4), and
        // shredded Pecorino the corpus's printed shredded PARMESAN pair, a
        // stand-in (v23 closer; 0669 line 4).
        (
          '¼ cup shredded Pecorino Romano cheese',
          "1/4 cup ≈ 59 mL · shredded, at ATK's printed 3 ounces = 1 cup · "
              'approximate (shredded Parmesan density)',
        ),
        ('¼ cup ghee, melted', '1/4 cup ≈ 59 mL · approximate (oil density)'),
        (
          '1 pound (2½ cups) dried pinto beans, picked over and rinsed',
          'from 1 pound · approximation (counted as Beans, navy, mature seeds, '
              'raw)',
        ),
        (
          '1 pound (2½ cups) dried beans, rinsed and picked over',
          'from 1 pound · approximation (counted as Beans, navy, mature seeds, '
              'raw)',
        ),
        (
          '1 pound (2 cups) dried small white beans, rinsed and picked over',
          'from 1 pound · approximation (counted as Beans, navy, mature seeds, '
              'raw)',
        ),
        (
          '16 cups spicy greens, such as arugula, watercress, mizuna, and baby '
              'mustard greens, washed and dried',
          '16 cup · USDA portion · approximation (counted as Arugula, raw)',
        ),
        (
          '2¼ cups (5 ounces) All-Bran Original cereal',
          'from 5 ounce · approximation (counted as Cereal, bran flakes, plain)',
        ),
        (
          '1¼ cups (6¼ ounces) seven-grain hot cereal mix',
          'from 6 1/4 ounce · approximation (counted as Cereals, whole wheat '
              'hot natural cereal, dry)',
        ),
        (
          '2 pounds fingerling potatoes, scrubbed, unpeeled',
          'from 2 pound · approximation (counted as Potatoes, red, without '
              'skin, raw)',
        ),
        (
          '3 cups tapioca starch',
          '3 cup · USDA portion · approximation (counted as Tapioca, pearl, '
              'dry)',
        ),
        ('3 tablespoons apple jelly', '3 tablespoon ≈ 44 mL'),
      ]) {
        final db = tempDb();
        final line = lineOf(raw);
        final row = await computeIn(db, line);
        expect(gramBasisFor(db, line, row), basis, reason: raw);
      }
    },
  );
}

/// The rows the v21 cache-only replay of snapshot 13 moved against v20's:
/// (corpus file, nutrition-line position, raw, the file's own line where
/// the parse of the raw differs, normalized item, fdc id, grams, rule — the
/// plan's Appendix A label; J5 the approved tapioca-starch stand-in —, the
/// row's review bucket and whether its confidence passes the gate, both
/// from the plan's r4 replay: 94 rows move on confidence alone, so the
/// bucket is the only thing their rule changes).
const List<
  (
    String,
    int,
    String,
    IngredientLine?,
    String,
    int?,
    String?,
    String,
    String,
    bool,
  )
>
_moved = [
  (
    '0002-hearty-chicken-noodle-soup.yaml',
    1,
    '1 pound ground chicken',
    null,
    'ground chicken',
    171116,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0007-tuscan-style-beef-stew.yaml',
    3,
    '1 (750-ml) bottle Chianti',
    null,
    'chianti',
    2710688,
    '750.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0008-our-favorite-chili.yaml',
    1,
    '8 ounces dried pinto beans (1¼ cups), picked over and rinsed',
    null,
    'dried pinto beans',
    173745,
    '226.80',
    'M2',
    'counted',
    true,
  ),
  (
    '0008-our-favorite-chili.yaml',
    3,
    '2–4 dried de árbol chiles, stemmed, seeded, and split into 2 pieces',
    null,
    'dried de arbol chiles',
    168570,
    '1.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0011-guay-tiew-tom-yum-goong-thai-hot-and-sour-noodle-soup-with-shrimp.yaml',
    1,
    '2 lemongrass stalks, trimmed to bottom 6 inches',
    null,
    'lemongrass stalks',
    168573,
    '20.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0012-quinoa-and-vegetable-stew.yaml',
    9,
    '1 cup prewashed white quinoa',
    null,
    'prewashed white quinoa',
    168874,
    '170.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0026-harira-moroccan-lentil-and-chickpea-soup.yaml',
    15,
    '1 cup brown lentils, picked over and rinsed',
    null,
    'brown lentils',
    2644283,
    // Since matcher v37 by ATK's printed 1 cup = 7 ounces.
    '198.45',
    'M1',
    'counted',
    true,
  ),
  (
    '0026-red-lentil-soup-with-warm-spices.yaml',
    14,
    '1½ teaspoons dried mint, crumbled',
    null,
    'dried mint',
    172239,
    '0.75',
    'M2',
    'counted',
    true,
  ),
  (
    '0033-caldo-verde.yaml',
    9,
    '1 pound collard greens, stemmed and cut into 1-inch pieces',
    null,
    'collard greens',
    2709576,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0035-vegetable-broth-base.yaml',
    3,
    '½ cup (½ ounce) parsley leaves and thin stems',
    null,
    'parsley leaves and stems',
    2709796,
    '14.17',
    'M1',
    'counted',
    true,
  ),
  (
    '0039-spicy-salad-with-mustard-and-balsamic-vinaigrette.yaml',
    6,
    '16 cups spicy greens, such as arugula, watercress, mizuna, and baby mustard greens, washed and dried',
    null,
    'spicy greens',
    169387,
    '320.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0046-mango-orange-and-jicama-salad.yaml',
    6,
    '2 mangos, peeled, pitted, and cut into ½-inch dice',
    null,
    'mangos',
    169910,
    '672.00',
    'G2/G3',
    'counted',
    true,
  ),
  (
    '0060-antipasto-pasta-salad.yaml',
    1,
    '8 ounces thick-sliced soppressata or salami, halved and cut into ¼-inch strips',
    null,
    'thick-sliced soppressata or salami',
    2706195,
    '226.80',
    'M1',
    'counted',
    true,
  ),
  (
    '0061-chilled-soba-noodles-with-cucumber-snow-peas-and-radishes.yaml',
    9,
    '4 ounces snow peas, strings removed, cut lengthwise into matchsticks',
    null,
    'snow peas',
    170010,
    '113.40',
    'M2',
    'counted',
    true,
  ),
  (
    '0067-skillet-lasagna.yaml',
    8,
    '10 curly-edged lasagna noodles, broken into 2-inch lengths',
    null,
    'curly-edged lasagna noodles',
    169736,
    '250.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0071-skillet-chicken-pot-pie-with-biscuit-topping.yaml',
    15,
    '2 cups frozen pea-carrot medley, thawed',
    null,
    'frozen pea-carrot medley',
    170425,
    '280.00',
    'M2',
    'counted',
    true,
  ),
  (
    '0074-roast-chicken-with-warm-bread-salad.yaml',
    5,
    '2 tablespoons champagne vinegar',
    null,
    'champagne vinegar',
    2709351,
    '30.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0089-braised-oxtails-with-white-beans-tomatoes-and-aleppo-pepper.yaml',
    8,
    '2 tablespoons ground dried Aleppo pepper',
    null,
    'ground dried aleppo pepper',
    169396,
    '13.90',
    'G6a',
    'counted',
    true,
  ),
  (
    '0101-arroz-con-pollo-latin-style-chicken-and-rice.yaml',
    7,
    '1 small green pepper, stemmed, seeded, and chopped fine',
    null,
    'green pepper',
    2258588,
    '119.00',
    'G5',
    'counted',
    true,
  ),
  (
    '0103-cuban-style-black-beans-and-rice.yaml',
    1,
    '6½ ounces dried black beans (1 cup), picked over and rinsed',
    null,
    'dried black beans',
    173734,
    '184.27',
    'M2',
    'counted',
    true,
  ),
  (
    '0109-palak-dal-spinach-dal-with-cumin-and-mustard-seeds.yaml',
    5,
    '3 tablespoons ghee',
    null,
    'ghee',
    171314,
    '40.81',
    'G6c',
    'counted',
    true,
  ),
  (
    '0109-palak-dal-spinach-dal-with-cumin-and-mustard-seeds.yaml',
    11,
    '4 whole dried arbol chiles',
    null,
    'whole dried arbol chiles',
    168570,
    '2.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0124-chicken-marbella.yaml',
    10,
    '2½–3 pounds bone-in split chicken breasts and/or leg quarters, trimmed',
    null,
    'bone-in split chicken breasts and or leg quarters',
    2727569,
    // v43 (Y2): AH-102's derived pieces (v39: the 0.608 class figure).
    '870.99',
    'M1',
    'counted',
    true,
  ),
  (
    '0150-oven-fried-chicken.yaml',
    6,
    '4 whole chicken legs, separated into drumsticks and thighs and skin removed',
    null,
    'whole chicken legs',
    173619,
    '1060.00',
    'G2/G3',
    'counted',
    true,
  ),
  (
    '0151-buffalo-wings.yaml',
    2,
    '2 tablespoons Tabasco or other hot sauce, plus more to taste',
    null,
    'tabasco or other hot sauce',
    2710093,
    '32.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0190-pan-seared-inexpensive-steaks.yaml',
    1,
    '2 1-pound whole boneless shell sirloin steaks (top butt) or whole flap meat steaks, each about 1¼ inches thick',
    null,
    '1-pound whole boneless shell sirloin steaks or whole flap meat steaks',
    2727574,
    '907.18',
    'M2',
    'counted',
    true,
  ),
  (
    '0231-thick-cut-pork-tenderloin-medallions.yaml',
    0,
    '2 (1- to 1¼-pound) pork tenderloins, trimmed, cut crosswise into 1½-inch pieces, and tied; thinner end pieces removed and tied together',
    null,
    'pork tenderloins',
    168312,
    // RE-PIN (M48): 1133.98 → 1020.58 g, the printed 1–1¼ lb range at its
    // midpoint (was its top); the basis names the range.
    '1020.58',
    'M2',
    'counted',
    true,
  ),
  (
    '0232-perfect-pan-seared-pork-tenderloin-steaks.yaml',
    0,
    '2 (1-pound) pork tenderloins, trimmed',
    null,
    'pork tenderloins',
    168312,
    '907.18',
    'M2',
    'counted',
    true,
  ),
  (
    '0233-pork-schnitzel-breaded-pork-cutlets.yaml',
    4,
    '1 (1¼-pound) pork tenderloin, trimmed of fat and silver skin and tenderloin cut on an angle into 4 equal pieces',
    null,
    'pork tenderloin',
    168312,
    '566.99',
    'M2',
    'counted',
    true,
  ),
  (
    '0234-pan-seared-oven-roasted-pork-tenderloin.yaml',
    0,
    '2 (12- to 16-ounce) pork tenderloins, trimmed of fat and silver skin',
    null,
    'pork tenderloins',
    168312,
    // RE-PIN (M48): 907.18 → 793.79 g, the printed 12–16 oz range at its
    // midpoint (was its top); the basis names the range.
    '793.79',
    'M2',
    'counted',
    true,
  ),
  (
    '0235-maple-glazed-pork-tenderloin.yaml',
    10,
    '2 (1¼- to 1½-pound) pork tenderloins, trimmed of fat and silver skin',
    null,
    'pork tenderloins',
    168312,
    // RE-PIN (M48): 1360.78 → 1247.38 g, the printed 1¼–1½ lb range at its
    // midpoint (was its top); the basis names the range.
    '1247.38',
    'M2',
    'counted',
    true,
  ),
  (
    '0236-broiled-pork-tenderloin.yaml',
    0,
    '2 (1-pound) pork tenderloins, trimmed',
    null,
    'pork tenderloins',
    168312,
    '907.18',
    'M2',
    'counted',
    true,
  ),
  (
    '0259-miso-marinated-salmon.yaml',
    0,
    '½ cup white miso paste',
    null,
    'white miso paste',
    172442,
    '137.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0268-oven-steamed-fish-with-scallions-and-ginger.yaml',
    5,
    '2 tablespoons rice wine or dry sherry',
    null,
    'rice wine or dry sherry',
    2710691,
    '29.28',
    'M1',
    'counted',
    true,
  ),
  (
    '0274-red-snapper-ceviche-with-radishes-and-orange.yaml',
    0,
    '1 pound skinless red snapper fillets, ½ inch thick',
    null,
    'skinless red snapper fillets',
    173698,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0274-red-snapper-ceviche-with-radishes-and-orange.yaml',
    10,
    '1 cup lightly salted popcorn',
    null,
    'lightly with salt popcorn',
    2708216,
    '14.00',
    'M2',
    'counted',
    true,
  ),
  (
    '0279-crispy-salt-and-pepper-shrimp.yaml',
    1,
    '2 tablespoons Chinese rice wine or dry sherry',
    null,
    'chinese rice wine or dry sherry',
    2710691,
    '29.28',
    'M1',
    'counted',
    true,
  ),
  (
    '0285-shrimp-cocktail.yaml',
    12,
    '1 teaspoon ancho or other mild chili powder',
    null,
    'ancho or other mild chili powder',
    171319,
    '2.71',
    'M1',
    'counted',
    true,
  ),
  (
    '0288-maryland-crab-cakes.yaml',
    0,
    '1 pound fresh jumbo lump crabmeat, carefully picked over to remove cartilage and shell fragments',
    null,
    'jumbo lump crabmeat',
    2684446,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0289-best-crab-cakes.yaml',
    0,
    '1 pound lump crabmeat, picked over for shells',
    null,
    'lump crabmeat',
    2684446,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0290-crab-towers-with-avocado-and-gazpacho-salsas.yaml',
    1,
    '1 tablespoon champagne vinegar',
    null,
    'champagne vinegar',
    2709351,
    '15.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0290-crab-towers-with-avocado-and-gazpacho-salsas.yaml',
    7,
    '12 ounces lump or backfin Atlantic blue crabmeat, carefully picked over to remove cartilage and shell fragments',
    null,
    'lump or backfin atlantic blue crabmeat',
    2684446,
    '340.19',
    'M2',
    'counted',
    true,
  ),
  (
    '0292-new-england-lobster-roll.yaml',
    8,
    '6 New England–style hot dog buns',
    null,
    'new england style hot dog buns',
    2707656,
    '270.00',
    'M2',
    'counted',
    true,
  ),
  (
    '0309-juicy-grilled-turkey-burgers.yaml',
    0,
    '1 (2-pound) bone-in turkey thigh, skinned, boned, trimmed, and cut into ½-inch pieces',
    null,
    'bone-in turkey thigh',
    174518,
    // v43 (Y6): AH-102 item 2598's meat (v39: the 0.608 class figure).
    '698.53',
    'M2',
    'counted',
    true,
  ),
  (
    '0309-philly-cheesesteaks.yaml',
    6,
    '8 slices white American cheese (8 ounces)',
    null,
    'white american cheese',
    2705764,
    '226.80',
    'M1',
    'counted',
    true,
  ),
  (
    '0315-oven-fried-onion-rings.yaml',
    7,
    '4 cups kettle-cooked potato chips',
    null,
    'kettle-cooked potato chips',
    2709422,
    '100.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0332-pasta-with-tomato-bacon-and-onion.yaml',
    7,
    '⅓ cup grated Pecorino Romano cheese',
    null,
    'pecorino romano cheese',
    171249,
    '18.90',
    'G6b',
    'counted',
    true,
  ),
  (
    '0334-penne-arrabbiata.yaml',
    9,
    '¼ cup grated Pecorino Romano, plus extra for serving',
    null,
    'pecorino romano',
    171249,
    '14.18',
    'G6b',
    'counted',
    true,
  ),
  (
    '0335-farfalle-with-pesto.yaml',
    2,
    '2 tablespoons fresh flat-leaf parsley leaves (optional)',
    null,
    'flat-leaf parsley leaves',
    2709796,
    '7.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0343-spaghetti-with-quick-mushroom-ragu.yaml',
    3,
    '8 ounces portobello mushroom caps, gills removed, caps cut into ½-inch pieces (about 1½ cups)',
    null,
    'portobello mushroom caps',
    2003598,
    '226.80',
    'M2',
    'counted',
    true,
  ),
  (
    '0345-orecchiette-with-broccoli-rabe-and-sausage.yaml',
    2,
    '8 ounces hot Italian sausage, casings removed',
    null,
    'hot italian sausage',
    171631,
    '226.80',
    'M2',
    'counted',
    true,
  ),
  (
    '0353-ragu-alla-bolognese.yaml',
    8,
    '6 ounces chicken livers, trimmed',
    null,
    'chicken livers',
    171060,
    '170.10',
    'M2',
    'counted',
    true,
  ),
  (
    '0353-ragu-alla-bolognese.yaml',
    11,
    '¾ pound ground veal',
    null,
    'ground veal',
    175290,
    '340.19',
    'M2',
    'counted',
    true,
  ),
  (
    '0363-classic-spaghetti-alla-carbonara.yaml',
    5,
    '¼ cup grated Pecorino Romano cheese',
    null,
    'pecorino romano cheese',
    171249,
    '14.18',
    'G6b',
    'counted',
    true,
  ),
  (
    '0371-simple-cheese-lasagna.yaml',
    19,
    '14 curly-edged lasagna noodles',
    null,
    'curly-edged lasagna noodles',
    169736,
    '350.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0371-simple-cheese-lasagna.yaml',
    22,
    '¼ cup grated Pecorino Romano cheese',
    null,
    'pecorino romano cheese',
    171249,
    '14.18',
    'G6b',
    'counted',
    true,
  ),
  (
    '0375-pastitsio.yaml',
    9,
    '1 teaspoon dried mint',
    null,
    'dried mint',
    172239,
    '0.50',
    'M2',
    'counted',
    true,
  ),
  (
    '0376-beijing-style-meat-sauce-and-noodles.yaml',
    2,
    '5 tablespoons red miso paste',
    null,
    'red miso paste',
    172442,
    '85.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0376-biang-biang-mian-flat-hand-pulled-noodles-with-chili-oil-vinaigrette.yaml',
    4,
    '10–20 bird chiles, ground fine',
    null,
    'bird chiles',
    168570,
    '7.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0395-pizza-bianca.yaml',
    7,
    '2 tablespoons whole fresh rosemary leaves',
    null,
    'whole rosemary leaves',
    173473,
    '3.40',
    'M1',
    'counted',
    true,
  ),
  (
    '0398-ultimate-grilled-pizza.yaml',
    0,
    '3 cups (16½ ounces) King Arthur bread flour',
    null,
    'king arthur bread flour',
    168913,
    '467.77',
    'M1',
    'counted',
    true,
  ),
  (
    '0402-italian-wedding-soup.yaml',
    22,
    '1 cup ditalini pasta',
    null,
    'ditalini pasta',
    169736,
    '91.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0412-parmesan-farrotto.yaml',
    0,
    '1½ cups whole farro',
    null,
    'whole farro',
    2710828,
    null,
    'M2',
    'no_grams',
    true,
  ),
  (
    '0434-french-potato-salad.yaml',
    4,
    '1½ tablespoons champagne vinegar or white wine vinegar',
    null,
    'champagne vinegar or white wine vinegar',
    2709351,
    '22.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0462-french-style-pork-stew.yaml',
    9,
    '1 meaty smoked ham shank or 2–3 smoked ham hocks (1¼ pounds)',
    null,
    'meaty smoked ham shank or 2 3 smoked ham hocks',
    2705900,
    '566.99',
    'M2',
    'counted',
    true,
  ),
  (
    '0467-pan-bagnat-provencal-tuna-sandwich.yaml',
    0,
    '1 vine-ripened tomato, cored and sliced thin',
    null,
    'vine-ripened tomato',
    170457,
    '123.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0467-pan-bagnat-provencal-tuna-sandwich.yaml',
    7,
    '½ cup fresh parsley leaves and tender stems',
    null,
    'parsley leaves and tender stems',
    2709796,
    '30.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0470-fresh-margaritas.yaml',
    5,
    '1 cup 100 percent agave tequila, preferably reposado',
    null,
    '100 percent agave tequila',
    2710705,
    '224.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0470-sangria.yaml',
    3,
    '1 (750-milliliter) bottle inexpensive, fruity, medium-bodied red wine, chilled',
    IngredientLine(
      raw:
          '1 (750-milliliter) bottle inexpensive, fruity, medium-bodied red wine, chilled',
      item: '(750-milliliter) inexpensive, fruity, medium-bodied red wine',
      prep: 'chilled',
      amounts: [
        Amount(
          measure: Measure.count,
          quantity: '1',
          unit: 'bottle',
          primary: true,
        ),
      ],
    ),
    'inexpensive fruity medium-bodied red wine',
    2710688,
    '750.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0472-quesadillas.yaml',
    2,
    '1 tablespoon minced pickled jalapeños (optional)',
    null,
    'pickled jalapenos',
    2710096,
    '9.38',
    'M1',
    'counted',
    true,
  ),
  (
    '0473-tortilla-soup.yaml',
    3,
    '2 bone-in, skin-on split chicken breasts (about 1½ pounds) or 4 bone-in, skin-on chicken thighs (about 1¼ pounds), skin removed and trimmed',
    null,
    'bone-in skin-on split chicken breasts or 4 bone-in',
    // v43 (Y3): its "skin removed" moves the breast to 2646170 at AH-102
    // 584's meat (v39: 2727569 at the 0.608 class figure).
    2646170,
    '442.25',
    'M1',
    'counted',
    true,
  ),
  (
    '0474-black-bean-soup.yaml',
    0,
    '1 pound (2 cups) dried black beans, rinsed and picked over',
    null,
    'dried black beans',
    173734,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0476-beef-empanadas.yaml',
    20,
    '½ cup cold vodka or tequila',
    null,
    'cold vodka or tequila',
    2710704,
    '112.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0482-tinga-de-pollo-shredded-chicken-tacos.yaml',
    5,
    '1 (14.5-ounce) can fire-roasted diced tomatoes',
    null,
    'fire-roasted diced tomatoes',
    333281,
    '411.07',
    'M1',
    'counted',
    true,
  ),
  (
    '0493-sous-vide-cochinita-pibil.yaml',
    4,
    '1 (4-inch) stick canela cinnamon',
    null,
    'canela cinnamon',
    171320,
    null,
    'M1',
    'no_grams',
    true,
  ),
  (
    '0493-sous-vide-cochinita-pibil.yaml',
    6,
    '2 tablespoons Mexican oregano',
    null,
    'mexican oregano',
    171328,
    '6.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0493-sous-vide-cochinita-pibil.yaml',
    13,
    '8 ounces banana leaf, cut into long strips and bruised',
    null,
    'banana leaf',
    null,
    null,
    'M3',
    'counted',
    true,
  ),
  (
    '0495-chili-con-carne.yaml',
    0,
    '3 medium ancho pods (about ½ ounce), toasted and ground, or 3 tablespoons ancho chile powder',
    null,
    'ancho pods',
    169396,
    '14.17',
    'M1',
    'counted',
    true,
  ),
  (
    '0498-best-vegetarian-chili.yaml',
    1,
    '1 pound (2½ cups) dried beans, rinsed and picked over',
    null,
    'dried beans',
    173745,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0506-chinese-pork-dumplings.yaml',
    8,
    '1 tablespoon Chinese rice wine or dry sherry',
    null,
    'chinese rice wine or dry sherry',
    2710691,
    '14.64',
    'M1',
    'counted',
    true,
  ),
  (
    '0506-pork-and-cabbage-dumplingswor-tip.yaml',
    16,
    '24 round gyoza wrappers',
    null,
    'gyoza wrappers',
    172802,
    // Since matcher v37 by the wonton wrapper's 8 g, flagged.
    '192.00',
    'M2',
    'counted',
    true,
  ),
  (
    '0508-shu-mai-steamed-chinese-dumplings.yaml',
    5,
    '4 dried shiitake mushroom caps (about ¾ ounce), soaked in hot water for 30 minutes, squeezed dry, and cut into ¼-inch dice',
    null,
    'dried shiitake mushroom caps',
    168436,
    '21.26',
    'M1',
    'counted',
    true,
  ),
  (
    '0510-goi-cuo-n-vietnamese-summer-rolls.yaml',
    15,
    '12 (8½-inch) round rice paper wrappers',
    IngredientLine(
      raw: '12 (8½-inch) round rice paper wrappers',
      item: '(8 1/2-inch) round rice paper wrappers',
      amounts: [
        Amount(
          measure: Measure.count,
          quantity: '12',
          primary: true,
        ),
      ],
    ),
    'round rice paper wrappers',
    2708166,
    '180.00',
    'M2',
    'counted',
    true,
  ),
  (
    '0511-shrimp-tempura.yaml',
    6,
    '1 cup seltzer water',
    null,
    'seltzer water',
    2710539,
    '236.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0513-sung-choy-bao-chicken-lettuce-wraps.yaml',
    1,
    '2 teaspoons Chinese rice wine or dry sherry',
    null,
    'chinese rice wine or dry sherry',
    2710691,
    '9.76',
    'M1',
    'counted',
    true,
  ),
  (
    '0513-sung-choy-bao-chicken-lettuce-wraps.yaml',
    6,
    '1 tablespoon Chinese rice wine or dry sherry',
    null,
    'chinese rice wine or dry sherry',
    2710691,
    '14.64',
    'M1',
    'counted',
    true,
  ),
  (
    '0514-thai-pork-lettuce-wraps.yaml',
    0,
    '1 (1-pound) pork tenderloin, trimmed of silver skin and fat, cut into 1-inch chunks, and frozen for 20 minutes',
    null,
    'pork tenderloin',
    168312,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0514-thai-pork-lettuce-wraps.yaml',
    2,
    '1 tablespoon white rice',
    null,
    'white rice',
    2512381,
    '12.57',
    'M1',
    'counted',
    true,
  ),
  (
    '0517-thai-style-chicken-soup.yaml',
    1,
    '3 stalks lemongrass, bottom 5 inches only, trimmed and sliced thin (see this page)',
    null,
    'lemongrass',
    168573,
    '30.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0517-thai-style-chicken-soup.yaml',
    13,
    '2 Thai, serrano, or jalapeño chiles, seeds and ribs removed, chiles sliced thin',
    null,
    'thai',
    2709798,
    '30.00',
    'M2',
    'counted',
    true,
  ),
  (
    '0519-sesame-noodles-with-shredded-chicken.yaml',
    9,
    '1 pound fresh Chinese noodles or 12 ounces dried spaghetti',
    IngredientLine(
      raw: '1 pound fresh Chinese noodles or 12 ounces dried spaghetti',
      item: 'fresh Chinese noodles',
      prep: 'or 12 ounces dried spaghetti',
      amounts: [
        Amount(
          measure: Measure.weight,
          quantity: '1',
          unit: 'pound',
          primary: true,
        ),
      ],
    ),
    'chinese noodles',
    169727,
    '453.59',
    'M1',
    'counted',
    true,
  ),
  (
    '0525-orange-flavored-chicken.yaml',
    11,
    '8 small whole dried red chiles (optional)',
    null,
    'whole dried red chiles',
    168570,
    '4.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0528-gongbao-jiding-sichuan-kung-pao-chicken.yaml',
    3,
    '1 tablespoon Chinese rice wine or dry sherry',
    null,
    'chinese rice wine or dry sherry',
    2710691,
    '14.64',
    'M1',
    'counted',
    true,
  ),
  (
    '0528-stir-fried-chicken-with-bok-choy-and-crispy-noodle-cake.yaml',
    7,
    '1 (9-ounce) package fresh Chinese noodles',
    null,
    'chinese noodles',
    169727,
    '255.15',
    'M1',
    'counted',
    true,
  ),
  (
    '0538-chinese-style-barbecued-spareribs.yaml',
    5,
    '½ cup Chinese rice wine or dry sherry',
    null,
    'chinese rice wine or dry sherry',
    2710691,
    '117.11',
    'M1',
    'counted',
    true,
  ),
  (
    '0538-stir-fried-pork-eggplant-and-onion-with-garlic-and-black-pepper.yaml',
    6,
    '1 (12-ounce) pork tenderloin, trimmed of fat and silver skin and cut into ¼-inch strips',
    null,
    'pork tenderloin',
    168312,
    '340.19',
    'M2',
    'counted',
    true,
  ),
  (
    '0540-pork-lo-mein.yaml',
    12,
    '¼ cup Chinese rice cooking wine (Shaoxing) or dry sherry',
    null,
    'chinese rice cooking wine or dry sherry',
    2710691,
    '58.56',
    'M1',
    'counted',
    true,
  ),
  (
    '0540-pork-lo-mein.yaml',
    16,
    '12 ounces fresh Chinese noodles or 8 ounces dried linguine',
    null,
    'chinese noodles or dried linguine',
    169727,
    '340.19',
    'M1',
    'counted',
    true,
  ),
  (
    '0540-sichuan-stir-fried-pork-in-garlic-sauce.yaml',
    5,
    '1 tablespoon Chinese rice wine or dry sherry',
    null,
    'chinese rice wine or dry sherry',
    2710691,
    '14.64',
    'M1',
    'counted',
    true,
  ),
  (
    '0540-sichuan-stir-fried-pork-in-garlic-sauce.yaml',
    11,
    '2 teaspoons Chinese rice wine or dry sherry',
    null,
    'chinese rice wine or dry sherry',
    2710691,
    '9.76',
    'M1',
    'counted',
    true,
  ),
  (
    '0542-mu-shu-pork.yaml',
    10,
    '1 (12-ounce) pork tenderloin, trimmed, halved horizontally, and sliced thin against grain',
    null,
    'pork tenderloin',
    168312,
    '340.19',
    'M2',
    'counted',
    true,
  ),
  (
    '0544-stir-fried-shrimp-with-snow-peas-and-red-bell-pepper-in-hot-and-sour-sauce.yaml',
    14,
    '½ pound snow peas or sugar snap peas, tips snapped off and strings removed',
    null,
    'snow peas or sugar snap peas',
    170010,
    '226.80',
    'M2',
    'counted',
    true,
  ),
  (
    '0545-kung-pao-shrimp.yaml',
    7,
    '1 tablespoon Chinese rice cooking wine (Shaoxing) or dry sherry',
    null,
    'chinese rice cooking wine or dry sherry',
    2710691,
    '14.64',
    'M1',
    'counted',
    true,
  ),
  (
    '0545-kung-pao-shrimp.yaml',
    13,
    '6 small whole dried red chiles',
    null,
    'whole dried red chiles',
    168570,
    '3.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0546-stir-fried-portobellos-with-ginger-oyster-sauce.yaml',
    14,
    '3 ounces snow peas, tips and strings removed',
    null,
    'snow peas',
    170010,
    '85.05',
    'M2',
    'counted',
    true,
  ),
  (
    '0554-shrimp-pad-thai.yaml',
    8,
    '3 tablespoons tamarind juice concentrate',
    null,
    'tamarind juice concentrate',
    2709269,
    // v32: sized by its volume sibling "Tamarinds, raw" (cup, pulp 120 g).
    '22.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0556-thai-grilled-beef-salad.yaml',
    2,
    '1 tablespoon white rice',
    null,
    'white rice',
    2512381,
    '12.57',
    'M1',
    'counted',
    true,
  ),
  (
    '0566-chicken-biryani.yaml',
    16,
    '1¼ cups basmati rice',
    null,
    'basmati rice',
    2512381,
    '251.37',
    'M1',
    'counted',
    true,
  ),
  (
    '0567-indian-curry.yaml',
    2,
    '4 green cardamom pods',
    null,
    'green cardamom pods',
    170919,
    '0.80',
    'M1',
    'counted',
    true,
  ),
  (
    '0570-falafel.yaml',
    0,
    '8 ounces dried chickpeas, picked over and rinsed',
    null,
    'dried chickpeas',
    173756,
    '226.80',
    'M2',
    'counted',
    true,
  ),
  (
    '0601-grilled-glazed-pork-tenderloin-roast.yaml',
    0,
    '2 (1-pound) pork tenderloins, trimmed',
    null,
    'pork tenderloins',
    168312,
    '907.18',
    'M2',
    'counted',
    true,
  ),
  (
    '0602-grilled-pork-tenderloin-with-grilled-pineapplered-onion-salsa.yaml',
    4,
    '2 (12- to 16-ounce) pork tenderloins, trimmed',
    null,
    'pork tenderloins',
    168312,
    // RE-PIN (M48): 907.18 → 793.79 g, the printed 12–16 oz range at its
    // midpoint (was its top); the basis names the range.
    '793.79',
    'M2',
    'counted',
    true,
  ),
  (
    '0603-grilled-pork-tenderloin-with-grilled-tomatoginger-salsa.yaml',
    4,
    '2 (12- to 16-ounce) pork tenderloins, trimmed',
    null,
    'pork tenderloins',
    168312,
    // RE-PIN (M48): 907.18 → 793.79 g, the printed 12–16 oz range at its
    // midpoint (was its top); the basis names the range.
    '793.79',
    'M2',
    'counted',
    true,
  ),
  (
    '0603-grilled-stuffed-pork-tenderloin.yaml',
    2,
    '2 (1¼- to 1½-pound) pork tenderloins, trimmed',
    null,
    'pork tenderloins',
    168312,
    // RE-PIN (M48): 1360.78 → 1247.38 g, the printed 1¼–1½ lb range at its
    // midpoint (was its top); the basis names the range.
    '1247.38',
    'M2',
    'counted',
    true,
  ),
  (
    '0608-grilled-pork-kebabs-with-hoisin-glaze.yaml',
    0,
    '2 (12-ounce) pork tenderloins, trimmed and cut into 1-inch chunks',
    null,
    'pork tenderloins',
    168312,
    '680.39',
    'M2',
    'counted',
    true,
  ),
  (
    '0631-peri-peri-grilled-chicken.yaml',
    0,
    '4–10 arbol chiles, stemmed',
    null,
    'arbol chiles',
    168570,
    '3.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0644-sweet-and-saucy-glazed-salmon.yaml',
    0,
    '½ cup jalapeño jelly',
    null,
    'jalapeno jelly',
    169642,
    '167.98',
    'M2',
    'counted',
    true,
  ),
  (
    '0648-grilled-blackened-red-snapper.yaml',
    9,
    '4 (6- to 8-ounce) skin-on red snapper fillets, ¾ inch thick',
    null,
    'skin-on red snapper fillets',
    173698,
    // RE-PIN (M48): 907.18 → 793.79 g, the printed 6–8 oz range at its midpoint
    // (was its top); the basis names the range.
    '793.79',
    'M2',
    'counted',
    true,
  ),
  (
    '0664-bread-and-butter-pickles.yaml',
    0,
    '2 pounds pickling cucumbers, ends trimmed, sliced ¼ inch thick',
    null,
    'pickling cucumbers',
    2346406,
    '907.18',
    'M1',
    'counted',
    true,
  ),
  (
    '0667-buttery-spring-vegetables.yaml',
    2,
    '8 ounces sugar snap peas, strings removed, trimmed',
    null,
    'sugar snap peas',
    170010,
    '226.80',
    'M2',
    'counted',
    true,
  ),
  (
    '0669-skillet-roasted-brussels-sprouts-with-lemon-and-pecorino-romano.yaml',
    4,
    '¼ cup shredded Pecorino Romano cheese',
    null,
    'pecorino romano cheese',
    171249,
    // v23 closer: shredded at the corpus's printed 3 ounces a cup.
    '21.26',
    'G6b',
    'counted',
    true,
  ),
  (
    '0672-buffalo-cauliflower-bites.yaml',
    10,
    '1 pound cauliflower florets, cut into 1½-inch pieces',
    null,
    'cauliflower florets',
    2685573,
    '453.59',
    'M1',
    'counted',
    true,
  ),
  (
    '0677-braised-eggplant-with-paprika-coriander-and-yogurt.yaml',
    0,
    '2 (8- to 10-ounce) globe or Italian eggplants',
    null,
    'globe or italian eggplants',
    2685577,
    // RE-PIN (M48): 566.99 → 510.29 g, the printed 8–10 oz range at its
    // midpoint (was its top); the basis names the range.
    '510.29',
    'M1',
    'counted',
    true,
  ),
  (
    '0679-boston-baked-beans.yaml',
    4,
    '1 pound (2 cups) dried small white beans, rinsed and picked over',
    null,
    'dried white beans',
    173745,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0679-drunken-beans.yaml',
    1,
    '1 pound (2½ cups) dried pinto beans, picked over and rinsed',
    null,
    'dried pinto beans',
    173745,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '0701-roasted-fingerling-potatoes-with-mixed-herbs.yaml',
    0,
    '2 pounds fingerling potatoes, scrubbed, unpeeled',
    null,
    'fingerling potatoes',
    2346402,
    '907.18',
    'M1',
    'counted',
    true,
  ),
  (
    '0710-rice-and-pasta-pilaf.yaml',
    2,
    '2 ounces vermicelli, broken into 1-inch pieces',
    null,
    'vermicelli',
    169736,
    '56.70',
    'M1',
    'counted',
    true,
  ),
  (
    '0711-mujaddara-rice-and-lentils-with-crispy-onions.yaml',
    4,
    '8½ ounces (1¼ cups) green or brown lentils, picked over and rinsed',
    null,
    'green or brown lentils',
    2644283,
    '240.97',
    'M1',
    'counted',
    true,
  ),
  (
    '0711-mujaddara-rice-and-lentils-with-crispy-onions.yaml',
    6,
    '1¼ cups basmati rice',
    null,
    'basmati rice',
    2512381,
    '251.37',
    'M1',
    'counted',
    true,
  ),
  (
    '0712-chelow-persian-style-rice-with-golden-crust.yaml',
    0,
    '2 cups basmati rice',
    null,
    'basmati rice',
    2512381,
    '402.20',
    'M1',
    'counted',
    true,
  ),
  (
    '0715-simple-israeli-couscous.yaml',
    0,
    '2 cups Israeli couscous',
    null,
    'israeli couscous',
    169699,
    '346.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0717-simple-farro.yaml',
    0,
    '1½ cups whole farro, rinsed',
    null,
    'whole farro',
    2710828,
    null,
    'M2',
    'no_grams',
    true,
  ),
  (
    '0718-no-fuss-creamy-parmesan-polenta.yaml',
    3,
    '1½ cups coarse-ground cornmeal',
    null,
    'coarse-ground cornmeal',
    169697,
    '234.22',
    'M1',
    'counted',
    true,
  ),
  (
    '0722-rich-and-creamy-scrambled-eggs.yaml',
    1,
    '2 large yolks',
    null,
    'yolks',
    748236,
    '34.00',
    'G5',
    'counted',
    true,
  ),
  (
    '0740-asparagus-ham-and-gruyere-frittata.yaml',
    6,
    '4 ounces ¼-inch-thick deli ham, cut into ½-inch cubes (about ¾ cup)',
    null,
    '1 4-inch-thick deli ham',
    332397,
    '113.40',
    'M1',
    'counted',
    true,
  ),
  (
    '0750-easy-buttermilk-waffles.yaml',
    9,
    '1¼ cups unflavored seltzer water or club soda',
    null,
    'unflavored seltzer water or club soda',
    2710539,
    '295.74',
    'M2',
    'counted',
    true,
  ),
  (
    '0762-bran-muffins.yaml',
    2,
    '2¼ cups (5 ounces) All-Bran Original cereal',
    null,
    'all-bran original cereal',
    2708456,
    '141.75',
    'M2',
    'counted',
    true,
  ),
  (
    '0762-bran-muffins.yaml',
    9,
    '3 tablespoons mild or light molasses',
    null,
    'mild or light molasses',
    168820,
    '62.55',
    'M1',
    'counted',
    true,
  ),
  (
    '0779-cold-brew-coffee-concentrate.yaml',
    1,
    '3½ cups filtered water, room temperature',
    null,
    'filtered water',
    null,
    null,
    'M3',
    'counted',
    true,
  ),
  (
    '0788-pao-de-queijo-brazilian-cheese-bread.yaml',
    0,
    '3 cups tapioca starch',
    null,
    'tapioca starch',
    169717,
    '456.00',
    'J5',
    'counted',
    true,
  ),
  (
    '0790-southern-cornbread.yaml',
    0,
    '4 teaspoons bacon drippings or vegetable oil',
    null,
    'bacon drippings or vegetable oil',
    2710180,
    '18.14',
    'M1',
    'counted',
    true,
  ),
  (
    '0791-fluffy-dinner-rolls.yaml',
    2,
    '½ cup cold milk',
    null,
    'cold milk',
    2705385,
    '122.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0809-multigrain-bread.yaml',
    0,
    '1¼ cups (6¼ ounces) seven-grain hot cereal mix',
    null,
    'seven-grain hot cereal mix',
    171667,
    '177.18',
    'M2',
    'counted',
    true,
  ),
  (
    '0816-molasses-spice-cookies.yaml',
    13,
    '½ cup light or dark molasses',
    null,
    'light or dark molasses',
    168820,
    '166.79',
    'M1',
    'counted',
    true,
  ),
  (
    '0840-pecan-or-walnut-crescent-cookies.yaml',
    0,
    '2 cups (8 ounces) whole pecans or walnuts, chopped fine',
    null,
    'whole pecans or walnuts',
    2346395,
    '226.80',
    'M1',
    'counted',
    true,
  ),
  (
    '0848-raspberry-squares.yaml',
    8,
    '1 cup raspberry preserves',
    null,
    'raspberry preserves',
    169641,
    '320.00',
    'M2',
    'counted',
    true,
  ),
  (
    '0849-key-lime-bars.yaml',
    0,
    '5 ounces animal crackers',
    null,
    'animal crackers',
    168014,
    '141.75',
    'M1',
    'counted',
    true,
  ),
  (
    '0862-oatmeal-cake-with-broiled-icing.yaml',
    0,
    '1 cup (3 ounces) quick-cooking oats',
    null,
    'quick-cooking oats',
    173904,
    '85.05',
    'M1',
    'counted',
    true,
  ),
  (
    '0895-flourless-chocolate-cake.yaml',
    3,
    '¼ cup strong coffee',
    null,
    'strong coffee',
    2710375,
    '60.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0910-tiramisu.yaml',
    8,
    '14 ounces (42 to 60, depending on size) dried ladyfingers',
    null,
    'dried ladyfingers',
    2707934,
    '396.89',
    'M2',
    'counted',
    true,
  ),
  (
    '0918-baked-alaska.yaml',
    0,
    '2 (1-pint) containers coffee ice cream',
    null,
    'coffee ice cream',
    168809,
    '527.87',
    'G4',
    'counted',
    true,
  ),
  (
    '0952-individual-fresh-berry-gratins-with-zabaglione.yaml',
    0,
    '3 cups (about 15 ounces) mixed berries (raspberries, blueberries, blackberries, and strawberries; strawberries hulled and halved lengthwise if small, quartered if large), at room temperature',
    null,
    'mixed berries',
    2709271,
    '425.24',
    'M1',
    'counted',
    true,
  ),
  (
    '0956-apple-strudel.yaml',
    9,
    '14 (14 by 9-inch) phyllo sheets, thawed',
    null,
    'phyllo sheets',
    172791,
    '266.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0958-skillet-apple-pie.yaml',
    12,
    '2½ pounds sweet and tart apples (about 4 large), peeled, cored, and cut into ½-inch-thick wedges',
    null,
    'sweet and tart apples',
    2709215,
    // v43 (Y8: peeled and cored apples × 0.78 (AH-102 item 17)).
    '884.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0977-classic-apple-pie.yaml',
    8,
    '2 pounds firm McIntosh apples (about 4 large), peeled, cored, and sliced ¼ inch thick',
    null,
    'firm mcintosh apples',
    2709215,
    // v43 (Y8: peeled and cored apples × 0.78 (AH-102 item 17)).
    '707.60',
    'M1',
    'counted',
    true,
  ),
  (
    '0978-deep-dish-apple-pie.yaml',
    2,
    '2½ pounds firm tart apples (about 5 large), peeled, cored, and sliced ¼ inch thick',
    null,
    'firm tart apples',
    2709215,
    // v43 (Y8: peeled and cored apples × 0.78 (AH-102 item 17)).
    '884.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0978-deep-dish-apple-pie.yaml',
    3,
    '2½ pounds firm sweet apples (about 5 large), peeled, cored, and sliced ¼ inch thick',
    null,
    'firm sweet apples',
    2709215,
    // v43 (Y8: peeled and cored apples × 0.78 (AH-102 item 17)).
    '884.50',
    'M1',
    'counted',
    true,
  ),
  (
    '0980-summer-berry-pie.yaml',
    8,
    '2 tablespoons red currant or apple jelly',
    null,
    'red currant or apple jelly',
    169642,
    '41.99',
    'M2',
    'counted',
    true,
  ),
  (
    '0981-sweet-cherry-pie.yaml',
    2,
    '2 red plums, halved and pitted',
    null,
    'red plums',
    169949,
    '132.00',
    'M1',
    'counted',
    true,
  ),
  (
    '0997-fresh-fruit-tart-with-pastry-cream.yaml',
    12,
    '½ cup red currant or apple jelly',
    null,
    'red currant or apple jelly',
    169642,
    '167.98',
    'M2',
    'counted',
    true,
  ),
  (
    '1000-linzertorte.yaml',
    11,
    '1¼ cups raspberry preserves',
    null,
    'raspberry preserves',
    169641,
    '400.00',
    'M2',
    'counted',
    true,
  ),
  (
    '1002-apple-galette.yaml',
    9,
    '3 tablespoons apple jelly',
    null,
    'apple jelly',
    169642,
    '62.99',
    'M2',
    'counted',
    true,
  ),
  (
    '1006-peach-tarte-tatin.yaml',
    4,
    '2 pounds ripe but firm peaches, peeled, pitted, and quartered',
    null,
    'ripe but firm peaches',
    325430,
    '907.18',
    'M1',
    'counted',
    true,
  ),
  (
    '1070-irish-stew-with-carrots-and-turnips.yaml',
    2,
    '3 medium-large onions, chopped coarse (about 5 cups)',
    null,
    'medium-large onions',
    170000,
    '800.00',
    'M2',
    'counted',
    true,
  ),
  (
    '1070-vospov-kofte-red-lentil-kofte.yaml',
    7,
    '1 teaspoon ground dried Aleppo pepper',
    null,
    'ground dried aleppo pepper',
    169396,
    '2.32',
    'G6a',
    'counted',
    true,
  ),
  (
    '1070-vospov-kofte-red-lentil-kofte.yaml',
    18,
    '½ teaspoon ground dried Aleppo pepper',
    null,
    'ground dried aleppo pepper',
    169396,
    '1.16',
    'G6a',
    'counted',
    true,
  ),
  (
    '1074-paella-de-verduras-cauliflower-and-bean-paella.yaml',
    10,
    '1 cup Calasparra or bomba rice',
    null,
    'calasparra or bomba rice',
    168879,
    '201.10',
    'M1',
    'counted',
    true,
  ),
  (
    '1082-pesce-allacqua-pazza-southern-italianstyle-poached-fish.yaml',
    0,
    '1½ pounds skin-on haddock fillets, ¾ to 1-inch thick',
    null,
    'skin-on haddock fillets',
    333374,
    '680.39',
    'M1',
    'counted',
    true,
  ),
  (
    '1087-dan-dan-mian-sichuan-noodles-with-chili-sauce-and-pork.yaml',
    7,
    '1½ teaspoons Chinese sesame paste or tahini',
    null,
    'chinese sesame paste or tahini',
    2707587,
    '7.50',
    'M1',
    'counted',
    true,
  ),
  (
    '1087-dan-dan-mian-sichuan-noodles-with-chili-sauce-and-pork.yaml',
    15,
    '1 pound fresh Chinese wheat noodles',
    null,
    'chinese wheat noodles',
    169727,
    '453.59',
    'M1',
    'counted',
    true,
  ),
  (
    '1089-braciole.yaml',
    6,
    '⅓ cup grated Pecorino Romano cheese, plus extra for serving',
    null,
    'pecorino romano cheese',
    171249,
    '18.90',
    'G6b',
    'counted',
    true,
  ),
  (
    '1093-vegan-baja-style-cauliflower-tacos.yaml',
    0,
    '3 cups (7½ ounces) coleslaw mix',
    null,
    'coleslaw mix',
    2346407,
    '212.62',
    'M2',
    'counted',
    true,
  ),
  (
    '1096-skillet-roasted-broccoli.yaml',
    1,
    '1¼ pounds broccoli crowns',
    null,
    'broccoli crowns',
    747447,
    '566.99',
    'M1',
    'counted',
    true,
  ),
  (
    '1111-lahmajun-armenian-flatbread.yaml',
    8,
    '¼ cup fresh parsley leaves and tender stems',
    null,
    'parsley leaves and tender stems',
    2709796,
    '15.00',
    'M1',
    'counted',
    true,
  ),
  (
    '1121-hearty-green-salad-with-chickpeas-pickled-cauliflower-and-seared-halloumi.yaml',
    3,
    '2 cups (1-inch) cauliflower florets',
    null,
    'cauliflower florets',
    2685573,
    // v38: weighed by its SR sibling's cup (169986, 107 g).
    '214.00',
    'M1',
    'counted',
    true,
  ),
  (
    '1121-hearty-green-salad-with-chickpeas-pickled-cauliflower-and-seared-halloumi.yaml',
    12,
    '½ teaspoon ground dried Aleppo pepper',
    null,
    'ground dried aleppo pepper',
    169396,
    '1.16',
    'G6a',
    'counted',
    true,
  ),
  (
    '1136-rose-sangria.yaml',
    1,
    '2 cups mixed berries',
    null,
    'mixed berries',
    2709271,
    '300.00',
    'M1',
    'counted',
    true,
  ),
  (
    '1138-stir-fried-beef-and-gai-lan.yaml',
    1,
    '1 pound gai lan, stalks trimmed',
    null,
    'gai lan',
    169404,
    '453.59',
    'M2',
    'counted',
    true,
  ),
  (
    '1139-alu-parathas-punjabi-potato-stuffed-griddle-breads.yaml',
    14,
    '¼ cup ghee, melted',
    null,
    'ghee',
    171314,
    '54.42',
    'G6c',
    'counted',
    true,
  ),
  (
    '1142-grilled-chicken-with-adobo-and-sazon.yaml',
    1,
    '2½ teaspoons commercial sazón',
    null,
    'commercial sazon',
    172242,
    '10.00',
    'M1',
    'counted',
    true,
  ),
  (
    '1145-clbr-turkish-poached-eggs-with-yogurt-and-spiced-butter.yaml',
    6,
    '1 teaspoon pul biber or ground dried Aleppo pepper',
    null,
    'pul biber or ground dried aleppo pepper',
    171329,
    '2.32',
    'G6a',
    'counted',
    true,
  ),
  (
    '1145-clbr-turkish-poached-eggs-with-yogurt-and-spiced-butter.yaml',
    7,
    '¼ teaspoon dried mint (optional)',
    null,
    'dried mint',
    172239,
    '0.13',
    'M2',
    'counted',
    true,
  ),
  (
    '1152-kanelbullar-swedish-cinnamon-buns.yaml',
    8,
    '2 teaspoons cardamom seeds, ground coarse',
    null,
    'cardamom seeds',
    170919,
    '4.00',
    'M1',
    'counted',
    true,
  ),
  (
    '1159-rhubarb-upside-down-cake.yaml',
    20,
    '2 tablespoons red currant jelly',
    null,
    'red currant jelly',
    169642,
    '41.99',
    'M2',
    'counted',
    true,
  ),
  (
    '1172-nikujaga-beef-and-potato-stew.yaml',
    6,
    '¼ cup sake or dry vermouth',
    null,
    'sake or dry vermouth',
    167723,
    '58.20',
    'M1',
    'counted',
    true,
  ),
  (
    '1183-pan-roasted-sea-bass-with-green-olive-almond-and-orange-relish.yaml',
    1,
    '½ cup toasted slivered almonds',
    null,
    'toasted slivered almonds',
    170567,
    '54.00',
    'M1',
    'counted',
    true,
  ),
  (
    '1184-monkfish-tagine.yaml',
    9,
    '½ teaspoon dried mint',
    null,
    'dried mint',
    172239,
    '0.25',
    'M2',
    'counted',
    true,
  ),
  (
    '1185-spicy-fried-chicken-sandwiches.yaml',
    12,
    '¼ cup jarred sliced jalapeños',
    null,
    'jarred jalapenos',
    2710096,
    '37.50',
    'M1',
    'counted',
    true,
  ),
  (
    '1186-ultimate-veggie-burgers.yaml',
    0,
    '¾ cup brown lentils, picked over and rinsed',
    null,
    'brown lentils',
    2644283,
    // Since matcher v37 by ATK's printed 1 cup = 7 ounces.
    '148.83',
    'M1',
    'counted',
    true,
  ),
  (
    '1187-rigatoni-with-tomatoes-bacon-and-fennel.yaml',
    6,
    '¼ teaspoon red pepper fakes',
    null,
    'red pepper fakes',
    170932,
    '0.45',
    'M1',
    'counted',
    true,
  ),
  (
    '1187-rigatoni-with-tomatoes-bacon-and-fennel.yaml',
    11,
    '¼ cup grated Pecorino Romano cheese, plus extra for serving',
    null,
    'pecorino romano cheese',
    171249,
    '14.18',
    'G6b',
    'counted',
    true,
  ),
  (
    '1192-gado-gado.yaml',
    14,
    '8 ounces cauliflower florets, cut into 1-inch pieces',
    null,
    'cauliflower florets',
    2685573,
    '226.80',
    'M1',
    'counted',
    true,
  ),
  (
    '1194-lumpiang-shanghai-with-seasoned-vinegar.yaml',
    16,
    '18–20 (8-inch) square lumpia wrappers or spring roll wrappers',
    IngredientLine(
      raw: '18–20 (8-inch) square lumpia wrappers or spring roll wrappers',
      item: '(8-inch) square lumpia wrappers or spring roll wrappers',
      amounts: [
        Amount(
          measure: Measure.count,
          quantity: '18–20',
          primary: true,
        ),
      ],
    ),
    'square lumpia wrappers or spring roll wrappers',
    172802,
    '608.00',
    'M2',
    'counted',
    true,
  ),
  (
    '1203-salted-caramel-apple-pie.yaml',
    10,
    '3 Fuji, Gala, or Golden Delicious apples, cored, quartered, and sliced very thin lengthwise',
    null,
    'fuji',
    1750340,
    '546.00',
    'G5',
    'counted',
    true,
  ),
  (
    '1206-chocolate-cherry-pie-pops.yaml',
    0,
    '1 cup cherry preserves',
    null,
    'cherry preserves',
    169641,
    '320.00',
    'M2',
    'counted',
    true,
  ),
  (
    '1208-albondigas-en-chipotle.yaml',
    7,
    '1 (14.5-ounce) can crushed fire-roasted tomatoes',
    null,
    'fire-roasted tomatoes',
    2685581,
    '411.07',
    'M1',
    'counted',
    true,
  ),
  (
    '1208-albondigas-en-chipotle.yaml',
    15,
    '12 ounces Mexican-style chorizo sausage, casings removed',
    null,
    'mexican-style chorizo sausage',
    173859,
    '340.19',
    'M2',
    'counted',
    true,
  ),
  (
    '1208-chraime.yaml',
    8,
    '1 tablespoon ground dried Aleppo pepper',
    null,
    'ground dried aleppo pepper',
    169396,
    '6.95',
    'G6a',
    'counted',
    true,
  ),
];
