// Real corpus lines wrap across adjacent literals; the gate keeps each
// corpus line verbatim, one literal per entry.
// ignore_for_file: lines_longer_than_80_chars

// Matcher v54 (Q25 — alcohol cooked off; matcherVersion 53; prep47
// design_q25_v2 with the owner's Q-a..Q-h, decided under the owner's
// 2026-10-07 standing authorization; zero requests): a counted row on one
// of the sixteen alcohol records keeps its record and grams, and its
// ETHANOL energy — the record's energy less Atwater 4/9/4 of its protein,
// fat and carbohydrate — counts only the share its cooking keeps (USDA
// Table of Nutrient Retention Factors R6, group 14, 5002–5009), read from
// the line's own steps; the row's flag says so.
//
// THE GATE (critic 11): every one of the library's 255 alcohol lines on
// snapshot 22 — the reader's kept %, its USDA code(s) and the FLAG it
// prints (so its minutes and its shape) — equal to q25_factors_v2.tsv as
// amended for Q-f, for closer1's D1 rulings (shrimp-scampi|5 Q-f 85;
// modern-beef-burgundy|9 17.92 by volume; broiled-chicken-with-gravy|11
// 25 min → 40; a stuffing rolled inside a rare roast is not cooked by it:
// beef-wellington|14 and 0216|7 at 2 min → 85), for the two rows the hand
// reading corrected (strawberry-rhubarb-pie|5 25 + 30 = 55 → 35;
// summer-peach-cake|1 50 / 70 by volume → 29.0) and for the minutes the
// corpus text prints where the table's script misread them
// (fix54/c_adj.tsv, every row read). Whole-recipe energies are the v54
// compute on recorded real FDC answers (FixtureProvider; no fixture added),
// each against the v53 tree's compute of the same recipe (4a1b340): only
// `energy` moves, by exactly the ethanol the retention removes.

import 'dart:convert';
import 'dart:io';

import 'package:logging/logging.dart';
import 'package:salt_server/src/config.dart';
import 'package:salt_server/src/db/salt_database.dart';
import 'package:salt_server/src/handlers/nutrition_handlers.dart';
import 'package:salt_server/src/nutrition/engine.dart';
import 'package:salt_server/src/nutrition/matcher.dart';
import 'package:salt_server/src/nutrition/provider.dart';
import 'package:salt_shared/salt_shared.dart';
import 'package:test/test.dart';

import 'support/corpus.dart';
import 'support/fdc_fixtures.dart';

const _source = 'atk-tv-2023';

/// The gate: (file, section title or null, position, raw, record, kept %,
/// USDA code(s), flag) — the reader's whole reading of each line.
const List<(String, String?, int, String, int, String, String, String?)>
_gate = [
  (
    '0005-best-beef-stew.yaml',
    null,
    8,
    '2 cups red wine',
    2710688,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 155 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0006-hearty-beef-and-vegetable-stew.yaml',
    null,
    9,
    '1½ cups dry red wine',
    2710688,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 160 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0007-alcatra-portuguese-style-beef-stew.yaml',
    null,
    7,
    '2¼ cups dry white wine',
    2710689,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 210 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0007-tuscan-style-beef-stew.yaml',
    null,
    3,
    '1 (750-ml) bottle Chianti',
    2710688,
    '23.49',
    '5008+5004+5002',
    'approximate (USDA retention: 2 cups cooked 137 min keeps 10 %; 1 cup cooked 17 min keeps 40 %; the rest cooked 5 min keeps 85 %)',
  ),
  (
    '0008-our-favorite-chili.yaml',
    null,
    16,
    '1 (12-ounce) bottle mild lager, such as Budweiser',
    2710616,
    '20.00',
    '5007',
    'approximate (USDA retention: alcohol cooked 90 min keeps 20 %)',
  ),
  (
    '0010-quick-beef-and-vegetable-soup.yaml',
    null,
    7,
    '½ cup red wine',
    2710688,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 26 min keeps 40 %)',
  ),
  (
    '0013-ultimate-cream-of-tomato-soup.yaml',
    null,
    9,
    '2 tablespoons brandy or dry sherry',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0014-creamless-creamy-tomato-soup.yaml',
    null,
    9,
    '2 tablespoons brandy (optional)',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0017-creamy-mushroom-soup.yaml',
    null,
    8,
    '⅓ cup Madeira or dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0017-mushroom-bisque.yaml',
    null,
    7,
    '2 tablespoons dry sherry',
    175112,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 20 min keeps 40 %)',
  ),
  (
    '0018-wild-rice-and-mushroom-soup.yaml',
    null,
    12,
    '⅔ cup dry sherry',
    175112,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 24 min keeps 40 %)',
  ),
  (
    '0024-hearty-lentil-soup.yaml',
    null,
    10,
    '½ cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 35 min keeps 35 %)',
  ),
  (
    '0030-farmhouse-vegetable-and-barley-soup.yaml',
    null,
    8,
    '⅓ cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 53 min keeps 35 %)',
  ),
  (
    '0061-chilled-soba-noodles-with-cucumber-snow-peas-and-radishes.yaml',
    null,
    3,
    '3 tablespoons mirin',
    2710692,
    '100.00',
    '',
    null,
  ),
  (
    '0071-skillet-chicken-pot-pie-with-biscuit-topping.yaml',
    null,
    11,
    '¼ cup dry vermouth or dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 10 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0073-skillet-beef-stroganoff.yaml',
    null,
    8,
    '⅓ cup brandy',
    2710699,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 40 min keeps 35 %)',
  ),
  (
    '0077-skillet-chicken-and-rice-with-peas-and-scallions.yaml',
    null,
    9,
    '½ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 19 min keeps 40 %)',
  ),
  (
    '0082-simple-pot-roast.yaml',
    null,
    12,
    '¼ cup dry red wine',
    2710688,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0083-old-fashioned-pot-roast.yaml',
    null,
    8,
    '½ cup dry red wine, plus ¼ cup for the sauce',
    2710688,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 210 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0083-pressure-cooker-pot-roast.yaml',
    null,
    10,
    '1 tablespoon red wine',
    2710688,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 5 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0084-catalan-style-beef-stew-with-mushrooms.yaml',
    null,
    7,
    '1½ cups dry white wine',
    2710689,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 150 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0085-carbonnade-a-la-flamande-belgian-beef-beer-and-onion-stew.yaml',
    null,
    9,
    '1½ cups (12-ounce bottle or can) dark beer or stout',
    2710616,
    '10.00',
    '5008',
    'approximate (USDA retention: alcohol cooked 120 min keeps 10 %)',
  ),
  (
    '0087-braised-beef-short-ribs.yaml',
    null,
    6,
    '2 cups red wine, such as Cabernet Sauvignon or Côtes du Rhône',
    2710688,
    '10.00',
    '5008',
    'approximate (USDA retention: alcohol cooked 133 min keeps 10 %)',
  ),
  (
    '0088-slow-cooker-beer-braised-short-ribs.yaml',
    null,
    6,
    '2 (12-ounce) bottles dark beer',
    2710616,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 605 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0093-cuban-style-picadillo.yaml',
    null,
    13,
    '¾ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 18 min keeps 40 %)',
  ),
  (
    '0094-shepherds-pie.yaml',
    null,
    14,
    '2 tablespoons Madeira or ruby port',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 12 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0095-chicken-and-dumplings.yaml',
    null,
    8,
    '¼ cup dry sherry',
    175112,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 75 min keeps 25 %)',
  ),
  (
    '0095-lighter-chicken-and-dumplings.yaml',
    null,
    6,
    '¼ cup dry sherry',
    175112,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 58 min keeps 35 %)',
  ),
  (
    '0096-best-chicken-stew.yaml',
    null,
    10,
    '1 cup dry white wine, plus extra for seasoning',
    2710689,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 87 min keeps 25 %)',
  ),
  (
    '0101-chicken-vesuvio.yaml',
    null,
    9,
    '1½ cups dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol poured over and baked 15 min keeps 85 %)',
  ),
  (
    '0105-paella.yaml',
    null,
    11,
    '⅓ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 25 min keeps 40 %)',
  ),
  (
    '0106-paella-on-the-grill.yaml',
    null,
    8,
    '⅔ cup dry sherry',
    175112,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 25 min keeps 40 %)',
  ),
  (
    '0108-cioppino.yaml',
    null,
    12,
    '1¼ cups dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 7 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0124-chicken-marbella.yaml',
    null,
    14,
    '⅓ cup white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 22 min keeps 40 %)',
  ),
  (
    '0125-braised-chicken-with-mustard-and-herbs.yaml',
    null,
    10,
    '⅓ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 26 min keeps 40 %)',
  ),
  (
    '0126-pollo-en-pepitoria-spanish-braised-chicken-with-sherry-and-saffron.yaml',
    null,
    7,
    '⅔ cup dry sherry',
    175112,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 50 min keeps 35 %)',
  ),
  (
    '0127-coq-au-riesling.yaml',
    null,
    8,
    '2½ cups dry Riesling',
    173200,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 36 min keeps 35 %)',
  ),
  (
    '0129-mahogany-chicken-thighs.yaml',
    null,
    2,
    '¼ cup dry sherry',
    175112,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 56 min keeps 35 %)',
  ),
  (
    '0132-pan-roasted-chicken-breasts-with-sage-vermouth-sauce.yaml',
    null,
    6,
    '½ cup dry vermouth',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 5 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0138-glazed-roast-chicken.yaml',
    null,
    4,
    '1 (16-ounce) can beer',
    2710616,
    '100.00',
    '',
    null,
  ),
  (
    '0154-classic-roast-turkey.yaml',
    'Giblet Pan Gravy',
    9,
    '1 cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 20 min keeps 40 %)',
  ),
  (
    '0162-roast-whole-turkey-breast-with-gravy.yaml',
    null,
    11,
    '¼ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 21 min keeps 40 %)',
  ),
  (
    '0163-turkey-and-gravy-for-a-crowd.yaml',
    null,
    11,
    '1 cup dry white wine',
    2710689,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 165 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0165-crisp-skin-high-roast-butterflied-turkey-with-sausage-dressing.yaml',
    'Turkey Gravy',
    7,
    '2 cups dry white wine',
    2710689,
    '20.00',
    '5007',
    'approximate (USDA retention: alcohol cooked 90 min keeps 20 %)',
  ),
  (
    '0167-easier-roast-turkey-and-gravy.yaml',
    null,
    11,
    '¼ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 10 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0172-braised-turkey.yaml',
    null,
    14,
    '1 cup dry white wine',
    2710689,
    '20.00',
    '5007',
    'approximate (USDA retention: alcohol cooked 105 min keeps 20 %)',
  ),
  (
    '0184-restaurant-style-herb-sauce-for-pan-seared-steaks.yaml',
    null,
    2,
    '½ cup white wine',
    2710689,
    '100.00',
    '',
    null,
  ),
  (
    '0184-restaurant-style-herb-sauce-for-pan-seared-steaks.yaml',
    'Sauce Base',
    7,
    '2 cups dry red wine',
    2710688,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 25 min keeps 40 %)',
  ),
  (
    '0194-pub-style-steak-and-ale-pie.yaml',
    null,
    12,
    '¾ cup beer',
    2710616,
    '20.00',
    '5007',
    'approximate (USDA retention: alcohol cooked 100 min keeps 20 %)',
  ),
  (
    '0209-red-winebraised-pork-chops.yaml',
    null,
    9,
    '½ cup red wine',
    2710688,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 83 min keeps 25 %)',
  ),
  (
    '0209-red-winebraised-pork-chops.yaml',
    null,
    10,
    '¼ cup ruby port',
    2710692,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 83 min keeps 25 %)',
  ),
  (
    '0211-french-style-pork-chops-with-apples-and-calvados.yaml',
    null,
    6,
    '½ cup Calvados',
    2710699,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol flamed, then cooked 25 min keeps 40 %)',
  ),
  (
    '0216-roast-beef-tenderloin-with-caramelized-onion-and-mushroom-stuffing.yaml',
    null,
    7,
    '½ cup Madeira or sweet Marsala wine',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0223-onion-braised-beef-brisket.yaml',
    null,
    11,
    '1 cup dry red wine',
    2710688,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 240 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0226-cuban-shredded-beef.yaml',
    null,
    8,
    '2 tablespoons dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 4 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0234-pan-seared-oven-roasted-pork-tenderloin.yaml',
    'Dried Cherry–Port Sauce with Onions and Marmalade',
    2,
    '¾ cup port',
    2710692,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 6 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0235-maple-glazed-pork-tenderloin.yaml',
    null,
    2,
    '2 tablespoons bourbon or brandy',
    2710700,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0237-milk-braised-pork-loin.yaml',
    null,
    8,
    '½ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0238-french-style-pot-roasted-pork-loin.yaml',
    null,
    9,
    '⅓ cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 50 min keeps 35 %)',
  ),
  (
    '0241-garlic-studded-roast-pork-loin.yaml',
    'Mustard–Shallot Sauce with Thyme',
    2,
    '¾ cup dry white wine or dry vermouth',
    2710689,
    '100.00',
    '',
    null,
  ),
  (
    '0244-slow-roasted-bone-in-pork-rib-roast.yaml',
    'Port Wine–Cherry Sauce',
    0,
    '2 cups tawny port',
    2710692,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 20 min keeps 40 %)',
  ),
  (
    '0246-slow-roasted-pork-shoulder-with-peach-sauce.yaml',
    null,
    5,
    '2 cups dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 30 min keeps 35 %)',
  ),
  (
    '0251-glazed-spiral-sliced-ham.yaml',
    'Cherry-Port Glaze',
    0,
    '½ cup ruby port',
    2710692,
    '100.00',
    '',
    null,
  ),
  (
    '0255-fish-and-chips.yaml',
    null,
    10,
    '1½ cups (12 ounces) cold beer',
    2710616,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 7 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0259-miso-marinated-salmon.yaml',
    null,
    2,
    '3 tablespoons sake',
    167723,
    '100.00',
    '',
    null,
  ),
  (
    '0259-miso-marinated-salmon.yaml',
    null,
    3,
    '3 tablespoons mirin',
    2710692,
    '100.00',
    '',
    null,
  ),
  (
    '0260-poached-salmon-with-herb-and-caper-vinaigrette.yaml',
    null,
    4,
    '½ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 15 min keeps 40 %)',
  ),
  (
    '0262-glazed-salmon.yaml',
    'Soy-Mustard Glaze',
    2,
    '2 tablespoons mirin',
    2710692,
    '100.00',
    '',
    null,
  ),
  (
    '0268-cod-baked-in-foil-with-leeks-and-carrots.yaml',
    null,
    8,
    '4 tablespoons vermouth or dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol poured over and baked 15 min keeps 85 %)',
  ),
  (
    '0268-oven-steamed-fish-with-scallions-and-ginger.yaml',
    null,
    5,
    '2 tablespoons rice wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol poured over and baked 12 min keeps 85 %)',
  ),
  (
    '0273-braised-halibut-with-leeks-and-mustard.yaml',
    null,
    5,
    '¾ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 12 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0279-crispy-salt-and-pepper-shrimp.yaml',
    null,
    1,
    '2 tablespoons Chinese rice wine or dry sherry',
    2710691,
    '100.00',
    '',
    null,
  ),
  (
    '0279-garlicky-shrimp-with-buttered-bread-crumbs.yaml',
    null,
    12,
    '⅓ cup dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 5 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0282-spanish-style-toasted-pasta-with-shrimp.yaml',
    null,
    13,
    '¼ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 13 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0283-greek-style-shrimp-with-tomatoes-and-feta.yaml',
    null,
    2,
    '3 tablespoons ouzo',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: 1 tablespoon cooked 6 min keeps 85 %; 2 tablespoons cooked 11 min keeps 85 %)',
  ),
  (
    '0283-greek-style-shrimp-with-tomatoes-and-feta.yaml',
    null,
    11,
    '¼ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 11 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0285-shrimp-cocktail.yaml',
    null,
    2,
    '1 cup dry white wine',
    2710689,
    '100.00',
    '',
    null,
  ),
  (
    '0291-flambeed-pan-roasted-lobster.yaml',
    null,
    2,
    '¼ cup bourbon or cognac',
    2710700,
    '75.00',
    '5003',
    'approximate (USDA retention: alcohol flamed keeps 75 %)',
  ),
  (
    '0291-flambeed-pan-roasted-lobster.yaml',
    null,
    5,
    '3 tablespoons dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0294-oven-steamed-mussels.yaml',
    null,
    3,
    '1 cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 16 min keeps 40 %)',
  ),
  (
    '0299-grown-up-grilled-cheese-sandwiches-with-cheddar-and-shallot.yaml',
    null,
    2,
    '2 tablespoons dry white wine or dry vermouth',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 12 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0303-turkey-tetrazzini.yaml',
    null,
    12,
    '¼ cup dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 13 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0324-fresh-pasta-without-a-machine.yaml',
    'Walnut Cream Sauce',
    1,
    '¾ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 3 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0326-pasta-with-creamy-tomato-sauce.yaml',
    null,
    9,
    '¼ cup plus 2 tablespoons dry white wine',
    2710689,
    '55.00',
    '5004+5002',
    'approximate (USDA retention: ¼ cup cooked 26 min keeps 40 %; 2 tablespoons stirred in off the heat keeps 85 %)',
  ),
  (
    '0330-marinara-sauce.yaml',
    null,
    5,
    '⅓ cup dry red wine',
    2710688,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 9 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0332-pasta-allamatriciana.yaml',
    null,
    4,
    '¼ cup red wine',
    2710688,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 12 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0335-pasta-with-cauliflower-bacon-and-bread-crumbs.yaml',
    null,
    9,
    '½ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 8 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0339-spring-vegetable-pasta.yaml',
    null,
    13,
    '1 cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 10 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0345-pasta-alla-norcina.yaml',
    null,
    11,
    '½ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0346-classic-shrimp-fra-diavolo.yaml',
    null,
    5,
    '¼ cup cognac or brandy',
    2710699,
    '75.00',
    '5003',
    'approximate (USDA retention: alcohol flamed keeps 75 %)',
  ),
  (
    '0346-classic-shrimp-fra-diavolo.yaml',
    null,
    8,
    '1 cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 9 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0346-garlicky-shrimp-pasta.yaml',
    null,
    7,
    '½ cup dry vermouth or white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0347-shrimp-fra-diavolo.yaml',
    null,
    4,
    '1 cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 16 min keeps 40 %)',
  ),
  (
    '0348-linguine-allo-scoglio-linguine-with-seafood.yaml',
    null,
    7,
    '1 cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 18 min keeps 40 %)',
  ),
  (
    '0349-rigatoni-with-beef-and-onion-ragu.yaml',
    null,
    8,
    '1 cup dry white wine',
    2710689,
    '47.50',
    '5008+5002',
    'approximate (USDA retention: ½ cup cooked 123 min keeps 10 %; ½ cup cooked 3 min keeps 85 %)',
  ),
  (
    '0350-beef-short-rib-ragu.yaml',
    null,
    8,
    '½ cup dry red wine',
    2710688,
    '10.00',
    '5008',
    'approximate (USDA retention: alcohol cooked 122 min keeps 10 %)',
  ),
  (
    '0352-pasta-and-slow-simmered-tomato-sauce-with-meat.yaml',
    null,
    4,
    '½ cup red wine',
    2710688,
    '20.00',
    '5007',
    'approximate (USDA retention: alcohol cooked 97 min keeps 20 %)',
  ),
  (
    '0353-ragu-alla-bolognese.yaml',
    null,
    15,
    '2 cups dry red wine',
    2710688,
    '20.00',
    '5007',
    'approximate (USDA retention: alcohol cooked 95 min keeps 20 %)',
  ),
  (
    '0354-fettuccine-with-slow-simmered-bolognese-sauce.yaml',
    null,
    7,
    '1 cup dry white wine',
    2710689,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 190 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0355-pasta-with-streamlined-bolognese-sauce.yaml',
    null,
    1,
    '1¼ cups sweet white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 25 min keeps 40 %)',
  ),
  (
    '0356-weeknight-tagliatelle-with-bolognese-sauce.yaml',
    null,
    12,
    '1 cup dry red wine',
    2710688,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 35 min keeps 35 %)',
  ),
  (
    '0358-classic-spaghetti-and-meatballs-for-a-crowd.yaml',
    null,
    20,
    '6 tablespoons dry white wine',
    2710689,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 75 min keeps 25 %)',
  ),
  (
    '0361-penne-alla-vodka-penne-with-vodka-sauce.yaml',
    null,
    7,
    '⅓ cup vodka',
    2710704,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 10 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0363-classic-spaghetti-alla-carbonara.yaml',
    null,
    2,
    '½ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 6 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0375-pastitsio.yaml',
    null,
    13,
    '¼ cup red wine',
    2710688,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 75 min keeps 25 %)',
  ),
  (
    '0382-one-hour-pizza.yaml',
    null,
    5,
    '¼ cup (2 ounces) mild lager',
    2710616,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 8 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0402-italian-wedding-soup.yaml',
    null,
    7,
    '½ cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 39 min keeps 35 %)',
  ),
  (
    '0403-italian-chicken-soup-with-parmesan-dumplings.yaml',
    null,
    6,
    '½ cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 35 min keeps 35 %)',
  ),
  (
    '0410-mushroom-risotto.yaml',
    null,
    13,
    '1 cup dry white wine or dry vermouth',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 19 min keeps 40 %)',
  ),
  (
    '0412-butternut-squash-risotto.yaml',
    null,
    10,
    '1½ cups dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 19 min keeps 40 %)',
  ),
  (
    '0414-chicken-marsala.yaml',
    null,
    8,
    '1½ cups sweet Marsala (see note)',
    2710692,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 5 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0415-better-chicken-marsala.yaml',
    null,
    0,
    '2¼ cups dry Marsala',
    175112,
    '45.00',
    '5004+5002',
    'approximate (USDA retention: 2 cups cooked 19 min keeps 40 %; ¼ cup cooked 3 min keeps 85 %)',
  ),
  (
    '0420-chicken-francese.yaml',
    null,
    4,
    '½ cup dry vermouth or white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 17 min keeps 40 %)',
  ),
  (
    '0421-chicken-saltimbocca.yaml',
    null,
    6,
    '1¼ cups dry vermouth or white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 5 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0422-chicken-canzanese.yaml',
    null,
    6,
    '2 cups dry white wine',
    2710689,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 80 min keeps 25 %)',
  ),
  (
    '0424-italian-sausage-with-grapes-and-balsamic-vinegar.yaml',
    null,
    7,
    '¼ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0426-beef-braised-in-barolo.yaml',
    null,
    10,
    '1 (750-milliliter) bottle Barolo wine',
    2710688,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 198 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0426-osso-buco.yaml',
    null,
    3,
    '2½ cups dry white wine',
    2710689,
    '10.00',
    '5008',
    'approximate (USDA retention: alcohol cooked 120 min keeps 10 %)',
  ),
  (
    '0428-shrimp-scampi.yaml',
    null,
    5,
    '1 tablespoon dry vermouth',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0428-ultimate-shrimp-scampi.yaml',
    null,
    4,
    '1 cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 11 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0432-classic-french-onion-soup.yaml',
    null,
    4,
    '½ cup dry sherry',
    175112,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 35 min keeps 35 %)',
  ),
  (
    '0433-streamlined-french-onion-soup.yaml',
    null,
    5,
    '¼ cup dry red wine',
    2710688,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 20 min keeps 40 %)',
  ),
  (
    '0448-french-style-stuffed-chicken-breasts.yaml',
    null,
    7,
    '½ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 19 min keeps 40 %)',
  ),
  (
    '0448-quick-chicken-fricassee.yaml',
    null,
    6,
    '¼ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 14 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0450-chicken-bouillabaisse.yaml',
    null,
    11,
    '½ cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 30 min keeps 35 %)',
  ),
  (
    '0450-chicken-bouillabaisse.yaml',
    null,
    14,
    '¼ cup pastis or Pernod',
    2710699,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 30 min keeps 35 %)',
  ),
  (
    '0451-coq-au-vin.yaml',
    null,
    9,
    '1 (750-milliliter) bottle medium-bodied red wine',
    2710688,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 40 min keeps 35 %)',
  ),
  (
    '0452-chicken-with-40-cloves-of-garlic.yaml',
    null,
    5,
    '¾ cup dry vermouth or dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol heated, time not printed, keeps 85 %)',
  ),
  (
    '0455-chicken-provencal.yaml',
    null,
    7,
    '1 cup dry white wine',
    2710689,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 81 min keeps 25 %)',
  ),
  (
    '0456-daube-provencal.yaml',
    null,
    11,
    '1 (750-milliliter) bottle bold red wine',
    2710688,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 151 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0457-beef-burgundy.yaml',
    null,
    15,
    '1 (750-milliliter) bottle red Burgundy or Pinot Noir',
    174835,
    '8.20',
    '5009+5002',
    'approximate (USDA retention: 3 cups cooked 170 min keeps 5 %; 2 tablespoons cooked 5 min keeps 85 %)',
  ),
  (
    '0457-beef-burgundy.yaml',
    null,
    17,
    '2 tablespoons brandy',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 5 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0458-slow-cooker-beef-burgundy.yaml',
    null,
    8,
    '2½ cups Pinot Noir',
    174835,
    '37.00',
    '5009+5002',
    'approximate (USDA retention: 1½ cups cooked 541 min keeps 5 %; 1 cup cooked 5 min keeps 85 %)',
  ),
  (
    '0459-modern-beef-burgundy.yaml',
    null,
    9,
    '1 (750-ml) bottle red Burgundy or Pinot Noir',
    174835,
    '17.92',
    '5009+5004',
    'approximate (USDA retention: 2 cups cooked 200 min keeps 5 %; the rest cooked 20 min keeps 40 %)',
  ),
  (
    '0461-beef-en-cocotte-with-mushroom-sauce.yaml',
    null,
    8,
    '¼ cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 52 min keeps 35 %)',
  ),
  (
    '0461-beef-en-cocotte-with-mushroom-sauce.yaml',
    null,
    9,
    '2 tablespoons cognac',
    2710699,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 52 min keeps 35 %)',
  ),
  (
    '0461-simplified-cassoulet-with-pork-and-kielbasa.yaml',
    null,
    16,
    '1½ cups dry white wine',
    2710689,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 75 min keeps 25 %)',
  ),
  (
    '0463-steak-au-poivre-with-brandied-cream-sauce.yaml',
    null,
    8,
    '¼ cup plus 1 tablespoon brandy',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: ¼ cup cooked 5 min keeps 85 %; 1 tablespoon stirred in off the heat keeps 85 %)',
  ),
  (
    '0464-steak-diane.yaml',
    null,
    5,
    '¼ cup cognac',
    2710699,
    '75.00',
    '5003',
    'approximate (USDA retention: alcohol flamed keeps 75 %)',
  ),
  (
    '0464-steak-diane.yaml',
    'Sauce Base for Steak Diane',
    7,
    '1½ cups dry red wine',
    2710688,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 35 min keeps 35 %)',
  ),
  (
    '0470-fresh-margaritas.yaml',
    null,
    5,
    '1 cup 100 percent agave tequila, preferably reposado',
    2710705,
    '100.00',
    '',
    null,
  ),
  (
    '0470-fresh-margaritas.yaml',
    null,
    6,
    '1 cup triple sec',
    2710623,
    '100.00',
    '',
    null,
  ),
  (
    '0470-sangria.yaml',
    null,
    3,
    '1 (750-milliliter) bottle inexpensive, fruity, medium-bodied red wine, chilled',
    2710688,
    '100.00',
    '',
    null,
  ),
  (
    '0470-sangria.yaml',
    null,
    4,
    '¼ cup triple sec',
    2710623,
    '100.00',
    '',
    null,
  ),
  (
    '0476-beef-empanadas.yaml',
    null,
    20,
    '½ cup cold vodka or tequila',
    2710704,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 25 min keeps 40 %)',
  ),
  (
    '0481-carne-deshebrada-shredded-beef-tacos.yaml',
    null,
    0,
    '1½ cups beer',
    2710616,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 150 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '0506-chinese-pork-dumplings.yaml',
    null,
    8,
    '1 tablespoon Chinese rice wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 10 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0506-pork-and-cabbage-dumplingswor-tip.yaml',
    null,
    2,
    '2 tablespoons mirin or sweet sherry',
    2710692,
    '100.00',
    '',
    null,
  ),
  (
    '0508-shu-mai-steamed-chinese-dumplings.yaml',
    null,
    9,
    '1 tablespoon dry sherry or Chinese rice cooking wine (Shaoxing)',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 8 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0511-shrimp-tempura.yaml',
    null,
    4,
    '1 cup vodka',
    2710704,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0513-sung-choy-bao-chicken-lettuce-wraps.yaml',
    null,
    1,
    '2 teaspoons Chinese rice wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 3 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0513-sung-choy-bao-chicken-lettuce-wraps.yaml',
    null,
    6,
    '1 tablespoon Chinese rice wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0516-negimaki-japanese-grilled-steak-and-scallion-rolls.yaml',
    null,
    3,
    '2 tablespoons mirin',
    2710692,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 3 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0516-negimaki-japanese-grilled-steak-and-scallion-rolls.yaml',
    null,
    4,
    '2 tablespoons sake',
    167723,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 3 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0524-chicken-teriyaki.yaml',
    null,
    5,
    '2 tablespoons mirin or sweet sherry',
    2710692,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0526-san-bei-ji-three-cup-chicken.yaml',
    null,
    1,
    '⅓ cup dry sherry',
    175112,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 19 min keeps 40 %)',
  ),
  (
    '0527-karaage-japanese-fried-chicken-thighs.yaml',
    null,
    1,
    '2 tablespoons sake',
    167723,
    '100.00',
    '',
    null,
  ),
  (
    '0528-gongbao-jiding-sichuan-kung-pao-chicken.yaml',
    null,
    3,
    '1 tablespoon Chinese rice wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 7 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0528-stir-fried-chicken-with-bok-choy-and-crispy-noodle-cake.yaml',
    null,
    2,
    '1 tablespoon dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0528-stir-fried-chicken-with-bok-choy-and-crispy-noodle-cake.yaml',
    null,
    13,
    '1 tablespoon dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0529-stir-fried-chicken-and-zucchini-with-ginger-sauce.yaml',
    null,
    3,
    '1 tablespoon dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0529-stir-fried-chicken-and-zucchini-with-ginger-sauce.yaml',
    null,
    7,
    '1 tablespoon dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0531-stir-fried-beef-and-broccoli-with-oyster-sauce.yaml',
    null,
    2,
    '1 tablespoon dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0532-beef-stir-fry-with-bell-peppers-and-black-pepper-sauce.yaml',
    null,
    4,
    '3 tablespoons dry sherry or Chinese rice wine',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: 1 tablespoon cooked 2 min keeps 85 %; 2 tablespoons stirred into hot liquid keeps 85 %)',
  ),
  (
    '0533-teriyaki-stir-fried-beef-with-green-beans-and-shiitakes.yaml',
    null,
    3,
    '1 tablespoon mirin or sweet sherry',
    2710692,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0535-chinese-braised-beef.yaml',
    null,
    2,
    '½ cup dry sherry',
    175112,
    '10.00',
    '5008',
    'approximate (USDA retention: alcohol cooked 146 min keeps 10 %)',
  ),
  (
    '0536-crispy-orange-beef.yaml',
    null,
    5,
    '2 tablespoons dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0538-chinese-barbecued-pork.yaml',
    null,
    4,
    '¼ cup dry sherry',
    175112,
    '100.00',
    '',
    null,
  ),
  (
    '0538-chinese-style-barbecued-spareribs.yaml',
    null,
    5,
    '½ cup Chinese rice wine or dry sherry',
    2710691,
    '20.00',
    '5007',
    'approximate (USDA retention: alcohol cooked 101 min keeps 20 %)',
  ),
  (
    '0540-pork-lo-mein.yaml',
    null,
    12,
    '¼ cup Chinese rice cooking wine (Shaoxing) or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 1 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0540-sichuan-stir-fried-pork-in-garlic-sauce.yaml',
    null,
    5,
    '1 tablespoon Chinese rice wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 1 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0540-sichuan-stir-fried-pork-in-garlic-sauce.yaml',
    null,
    11,
    '2 teaspoons Chinese rice wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 4 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0542-mu-shu-pork.yaml',
    null,
    6,
    '2 tablespoons dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0544-stir-fried-shrimp-with-snow-peas-and-red-bell-pepper-in-hot-and-sour-sauce.yaml',
    null,
    8,
    '1 tablespoon dry sherry or Chinese rice cooking wine (Shaoxing)',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 1 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0545-kung-pao-shrimp.yaml',
    null,
    7,
    '1 tablespoon Chinese rice cooking wine (Shaoxing) or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 1 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0591-grill-roasted-beef-short-ribs.yaml',
    'Blackberry Glaze',
    2,
    '¼ cup bourbon',
    2710700,
    '100.00',
    '',
    null,
  ),
  (
    '0601-grilled-glazed-pork-tenderloin-roast.yaml',
    'Miso Glaze',
    0,
    '3 tablespoons sake',
    167723,
    '100.00',
    '',
    null,
  ),
  (
    '0601-grilled-glazed-pork-tenderloin-roast.yaml',
    'Miso Glaze',
    1,
    '3 tablespoons mirin',
    2710692,
    '100.00',
    '',
    null,
  ),
  (
    '0606-smoked-pork-loin-with-dried-fruit-chutney.yaml',
    null,
    5,
    '¾ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 14 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0627-grilled-glazed-bone-in-chicken-breasts.yaml',
    'Soy-Ginger Glaze',
    2,
    '2 tablespoons mirin',
    2710692,
    '100.00',
    '',
    null,
  ),
  (
    '0640-grill-roasted-beer-can-chicken.yaml',
    null,
    0,
    '1 (12-ounce) can beer',
    2710616,
    '100.00',
    '',
    null,
  ),
  (
    '0666-stir-fried-asparagus-with-shiitake-mushrooms.yaml',
    null,
    2,
    '1 tablespoon dry sherry',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 1 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0679-drunken-beans.yaml',
    null,
    7,
    '½ cup tequila',
    2710705,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 78 min keeps 25 %)',
  ),
  (
    '0679-drunken-beans.yaml',
    null,
    9,
    '1 cup Mexican lager',
    2710616,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 30 min keeps 35 %)',
  ),
  (
    '0687-sauteed-mushrooms-with-red-wine-and-rosemary.yaml',
    null,
    8,
    '¼ cup red wine',
    2710688,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 5 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0695-mashed-potatoes-with-blue-cheese-and-port-caramelized-onions.yaml',
    null,
    5,
    '1 cup ruby port',
    2710692,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 4 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0699-root-vegetable-gratin.yaml',
    null,
    4,
    '⅔ cup dry white wine',
    2710689,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 85 min keeps 25 %)',
  ),
  (
    '0713-almost-hands-free-risotto-with-parmesan-and-herbs.yaml',
    null,
    7,
    '1 cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 21 min keeps 40 %)',
  ),
  (
    '0719-spiced-pecans-with-rum-glaze.yaml',
    null,
    6,
    '1 tablespoon rum, preferably dark, or water',
    2710703,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 1 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0743-breakfast-strata-with-spinach-and-gruyere.yaml',
    null,
    5,
    '½ cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 52 min keeps 35 %)',
  ),
  (
    '0776-strawberries-and-grapes-with-balsamic-and-red-wine-reduction.yaml',
    null,
    1,
    '¼ cup dry red wine',
    2710688,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 15 min keeps 40 %)',
  ),
  (
    '0798-almost-no-knead-bread.yaml',
    null,
    4,
    '6 tablespoons mild-flavored lager',
    2710616,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 50 min keeps 35 %)',
  ),
  (
    '0853-holiday-eggnog.yaml',
    null,
    4,
    '½ cup brandy, bourbon, or dark rum',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0866-french-apple-cake.yaml',
    null,
    1,
    '1 tablespoon Calvados',
    2710699,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 75 min keeps 25 %)',
  ),
  (
    '0871-gateau-breton-with-apricot-filling.yaml',
    null,
    7,
    '2 tablespoons dark rum',
    2710703,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 45 min keeps 35 %)',
  ),
  (
    '0872-strawberry-cream-cake.yaml',
    null,
    10,
    '2 tablespoons kirsch',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 3 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0875-summer-peach-cake.yaml',
    null,
    1,
    '5 tablespoons peach schnapps',
    2710623,
    '29.00',
    '5005+5006',
    'approximate (USDA retention: 2 tablespoons cooked 50 min keeps 35 %; 3 tablespoons cooked 70 min keeps 25 %)',
  ),
  (
    '0876-classic-gingerbread-cake.yaml',
    null,
    0,
    '¾ cup stout, such as Guinness',
    2710616,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 35 min keeps 35 %)',
  ),
  (
    '0898-individual-sticky-toffee-pudding-cakes.yaml',
    null,
    15,
    '1 tablespoon rum',
    2710703,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 3 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0899-bittersweet-chocolate-roulade.yaml',
    'Dark Chocolate Ganache',
    3,
    '1 tablespoon cognac',
    2710699,
    '100.00',
    '',
    null,
  ),
  (
    '0905-chocolate-volcano-cakes-with-espresso-ice-cream.yaml',
    null,
    8,
    '2 teaspoons Grand Marnier (or other orange-flavored liqueur)',
    2710623,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 16 min keeps 40 %)',
  ),
  (
    '0906-chocolate-espresso-dacquoise.yaml',
    null,
    12,
    '2 tablespoons amaretto or water',
    2710623,
    '100.00',
    '',
    null,
  ),
  (
    '0910-tiramisu.yaml',
    null,
    1,
    '9 tablespoons dark rum',
    2710703,
    '100.00',
    '',
    null,
  ),
  (
    '0924-best-butterscotch-pudding.yaml',
    null,
    12,
    '1 teaspoon dark rum',
    2710703,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0932-dark-chocolate-mousse.yaml',
    null,
    3,
    '1 tablespoon brandy',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0936-grand-marnier-souffle.yaml',
    null,
    10,
    '3 tablespoons Grand Marnier',
    2710623,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 20 min keeps 40 %)',
  ),
  (
    '0939-make-ahead-chocolate-souffles.yaml',
    null,
    4,
    '1 tablespoon Grand Marnier',
    2710623,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 12 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0949-sour-cherry-cobbler.yaml',
    null,
    11,
    '1 cup dry red wine',
    2710688,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 15 min keeps 40 %)',
  ),
  (
    '0952-individual-fresh-berry-gratins-with-zabaglione.yaml',
    null,
    5,
    '3 tablespoons dry white wine, such as Sauvignon Blanc',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 5 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0957-easy-apple-strudel.yaml',
    null,
    1,
    '2 tablespoons Calvados or apple cider',
    2710699,
    '100.00',
    '',
    null,
  ),
  (
    '0959-bananas-foster.yaml',
    null,
    4,
    '4 tablespoons dark rum',
    2710703,
    '77.50',
    '5002+5003',
    'approximate (USDA retention: 1 tablespoon cooked 5 min keeps 85 %; 3 tablespoons flamed keeps 75 %)',
  ),
  (
    '0960-crepes-suzette.yaml',
    null,
    6,
    '2 tablespoons cognac',
    2710699,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0960-crepes-suzette.yaml',
    null,
    8,
    '4 tablespoons cognac',
    2710699,
    '77.50',
    '5003+5002',
    'approximate (USDA retention: 3 tablespoons flamed keeps 75 %; 1 tablespoon stirred into hot liquid keeps 85 %)',
  ),
  (
    '0960-crepes-suzette.yaml',
    null,
    12,
    '2 tablespoons orange-flavored liqueur, preferably triple sec',
    2710623,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '0964-roasted-pears-with-dried-apricots-and-pistachios.yaml',
    null,
    2,
    '1¼ cups dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 7 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '0968-summer-berry-trifle.yaml',
    null,
    25,
    '1 tablespoon plus ½ cup cream sherry',
    2710692,
    '100.00',
    '',
    null,
  ),
  (
    '0974-foolproof-double-crust-pie-dough.yaml',
    null,
    5,
    '¼ cup vodka, chilled',
    2710704,
    '100.00',
    '',
    null,
  ),
  (
    '0974-foolproof-double-crust-pie-dough.yaml',
    'Foolproof Single-Crust Pie Dough',
    5,
    '2 tablespoons vodka, chilled',
    2710704,
    '100.00',
    '',
    null,
  ),
  (
    '0981-sweet-cherry-pie.yaml',
    null,
    7,
    '2 teaspoons bourbon (optional)',
    2710700,
    '25.00',
    '5006',
    'approximate (USDA retention: alcohol cooked 65 min keeps 25 %)',
  ),
  (
    '0986-strawberry-rhubarb-pie.yaml',
    null,
    5,
    '¼ cup vodka, chilled',
    2710704,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 55 min keeps 35 %)',
  ),
  (
    '0991-coconut-cream-pie.yaml',
    null,
    12,
    '1½ teaspoons dark rum (optional)',
    2710703,
    '100.00',
    '',
    null,
  ),
  (
    '1005-30-minute-tarte-tatin.yaml',
    null,
    5,
    '2 tablespoons Grand Marnier, spiced rum, or Calvados (optional)',
    2710623,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
  ),
  (
    '1006-peach-tarte-tatin.yaml',
    null,
    5,
    '1 tablespoon bourbon (optional)',
    2710700,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1074-albondigas-en-salsa-de-almendras-spanish-style-meatballs-in-almond-sauce.yaml',
    null,
    17,
    '½ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 7 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1074-paella-de-verduras-cauliflower-and-bean-paella.yaml',
    null,
    9,
    '¼ cup dry sherry',
    175112,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 21 min keeps 40 %)',
  ),
  (
    '1076-broiled-chicken-with-gravy.yaml',
    null,
    11,
    '¼ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 25 min keeps 40 %)',
  ),
  (
    '1081-crispy-fish-sandwiches-with-tartar-sauce.yaml',
    null,
    10,
    '¾ cup beer',
    2710616,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 8 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1082-pesce-allacqua-pazza-southern-italianstyle-poached-fish.yaml',
    null,
    9,
    '¼ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 4 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1087-dan-dan-mian-sichuan-noodles-with-chili-sauce-and-pork.yaml',
    null,
    9,
    '2 teaspoons Shaoxing wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 8 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1089-braciole.yaml',
    null,
    16,
    '¾ cup dry red wine',
    2710688,
    '5.00',
    '5009',
    "approximate (USDA retention: alcohol cooked 150 min keeps 5 %, the table's 2½-hour figure)",
  ),
  (
    '1089-shrimp-risotto.yaml',
    null,
    12,
    '¾ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 21 min keeps 40 %)',
  ),
  (
    '1092-poulet-au-vinaigre-chicken-with-vinegar.yaml',
    null,
    7,
    '1 cup dry white wine',
    2710689,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 40 min keeps 35 %)',
  ),
  (
    '1093-shizi-tou-lions-head-meatballs.yaml',
    null,
    6,
    '2 tablespoons Shaoxing wine or dry sherry',
    2710691,
    '20.00',
    '5007',
    'approximate (USDA retention: alcohol cooked 90 min keeps 20 %)',
  ),
  (
    '1097-patatas-panaderas-spanish-potatoes-with-olive-oil-and-wine.yaml',
    null,
    6,
    '½ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol poured over and baked 20 min keeps 85 %)',
  ),
  (
    '1120-cataplana-portuguese-seafood-stew.yaml',
    null,
    12,
    '½ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 10 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1125-roast-whole-turkey-breast-with-gravy.yaml',
    null,
    11,
    '¼ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 21 min keeps 40 %)',
  ),
  (
    '1129-beef-wellington.yaml',
    null,
    14,
    '1 tablespoon Madeira',
    175112,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1133-chicken-francese.yaml',
    null,
    11,
    '⅓ cup dry white wine',
    2710689,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 9 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1133-paniscia-red-wine-risotto-with-beans.yaml',
    null,
    11,
    '1 cup dry red wine',
    2710688,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 21 min keeps 40 %)',
  ),
  (
    '1134-tartiflette-french-potato-and-cheese-gratin.yaml',
    null,
    7,
    '½ cup dry white wine',
    2710689,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 22 min keeps 40 %)',
  ),
  (
    '1136-rose-sangria.yaml',
    null,
    0,
    '2 (750-ml) bottles rosé wine',
    2710690,
    '100.00',
    '',
    null,
  ),
  (
    '1136-rose-sangria.yaml',
    null,
    3,
    '4 ounces elderflower liqueur',
    2710623,
    '100.00',
    '',
    null,
  ),
  (
    '1138-stir-fried-beef-and-gai-lan.yaml',
    null,
    2,
    '5 teaspoons Shaoxing wine or dry sherry, divided',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: 1 teaspoon cooked 2 min keeps 85 %; 4 teaspoons stirred into hot liquid keeps 85 %)',
  ),
  (
    '1145-xihongshi-chao-jidan-chinese-stir-fried-tomatoes-and-eggs.yaml',
    null,
    5,
    '2 tablespoons Shaoxing wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1148-gravlax.yaml',
    null,
    3,
    '3 tablespoons brandy',
    2710699,
    '100.00',
    '',
    null,
  ),
  (
    '1155-champagne-cocktail.yaml',
    null,
    2,
    '5½ fluid ounces (½ cup plus 3 tablespoons) champagne, chilled',
    2710689,
    '100.00',
    '',
    null,
  ),
  (
    '1172-nikujaga-beef-and-potato-stew.yaml',
    null,
    6,
    '¼ cup sake or dry vermouth',
    167723,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 25 min keeps 40 %)',
  ),
  (
    '1172-nikujaga-beef-and-potato-stew.yaml',
    null,
    9,
    '¼ cup mirin',
    2710692,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 25 min keeps 40 %)',
  ),
  (
    '1177-multicooker-chicken-in-a-pot-with-lemon-herb-sauce.yaml',
    null,
    5,
    '½ cup dry white wine',
    2710689,
    '100.00',
    '',
    null,
  ),
  (
    '1178-chicken-teriyaki.yaml',
    null,
    1,
    '3½ tablespoons sake, divided',
    167723,
    '85.00',
    '5002',
    'approximate (USDA retention: 1½ tablespoons cooked 8 min keeps 85 %; 2 tablespoons cooked 1 min keeps 85 %)',
  ),
  (
    '1182-pot-roast-with-root-vegetables.yaml',
    null,
    15,
    '⅓ cup red wine',
    2710688,
    '40.00',
    '5004',
    'approximate (USDA retention: alcohol cooked 15 min keeps 40 %)',
  ),
  (
    '1188-weeknight-pasta-bolognese.yaml',
    null,
    11,
    '1 cup dry red wine',
    2710688,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 35 min keeps 35 %)',
  ),
  (
    '1192-braised-lamb-shanks-with-red-wine-and-herbes-de-provence.yaml',
    null,
    9,
    '2 cups dry red wine',
    2710688,
    '10.00',
    '5008',
    'approximate (USDA retention: alcohol cooked 135 min keeps 10 %)',
  ),
  (
    '1193-stir-fried-cumin-beef.yaml',
    null,
    9,
    '1 tablespoon Shaoxing wine or dry sherry',
    2710691,
    '85.00',
    '5002',
    'approximate (USDA retention: alcohol cooked 2 min keeps 85 %, the stirred-into-hot-liquid figure)',
  ),
  (
    '1197-stollen.yaml',
    null,
    5,
    '½ cup (4 ounces) brandy',
    2710699,
    '35.00',
    '5005',
    'approximate (USDA retention: alcohol cooked 41 min keeps 35 %)',
  ),
];

/// Whole recipes on the recorded fixtures: (file, energy a batch on the v53
/// tree, energy a batch now, carbohydrate and protein — the same on both
/// trees, [(position, record, grams, kept %)] of the alcohol rows).
const List<
  (String, double, double, double, double, List<(int, int, double, double)>)
>
_whole = [
  // P8: 2 + 90 + 45 + 15 + 3 = 155 min → 5009 5 % (468.44 g red wine)
  (
    '0005-best-beef-stew.yaml',
    4937.85,
    4607.28,
    189.36,
    389.59,
    [(8, 2710688, 468.44, 5)],
  ),
  // P10 restated: 180 + the skimmed liquid reduced 18 = 198 min → 5 %
  (
    '0426-beef-braised-in-barolo.yaml',
    3666.73,
    3137.48,
    0,
    0,
    [(10, 2710688, 750.00, 5)],
  ),
  // Q-f: "Off heat, stir in brandy" into the hot soup → 5002 85 %
  (
    '0013-ultimate-cream-of-tomato-soup.yaml',
    1545.22,
    1535.07,
    133.07,
    30.32,
    [(9, 2710699, 29.28, 85)],
  ),
  // P1: brought to a simmer, ladled → boil-off 85 %
  (
    '0017-creamy-mushroom-soup.yaml',
    2408.67,
    2396.43,
    0,
    0,
    [(8, 175112, 78.07, 85)],
  ),
  // D1 (Q-f extended): "Off the heat, add the lemon juice and vermouth"
  ('0428-shrimp-scampi.yaml', 1377.47, 1375.16, 0, 0, [(5, 175112, 14.75, 85)]),
  // D1 (the shape): Madeira cooked 2–3 min, the stuffing rolled in a rare roast
  (
    '0216-roast-beef-tenderloin-with-caramelized-onion-and-mushroom-stuffing.yaml',
    2813.50,
    2795.14,
    0,
    0,
    [(7, 175112, 117.11, 85)],
  ),
  // P13: the batter on the fish, fried 7–8 → 85 %
  (
    '0255-fish-and-chips.yaml',
    3977.24,
    3963.48,
    0,
    0,
    [(10, 2710616, 340.19, 85)],
  ),
  // P21: |6 the batter's crepes (sub-minute → 5002), |8 3 T flamed + 1 T
  // into the hot sauce (75/85 by volume = 77.5), |12 the liqueur (85)
  (
    '0960-crepes-suzette.yaml',
    3095.29,
    3049.95,
    312.00,
    57.24,
    [
      (6, 2710699, 28.00, 85),
      (8, 2710699, 56.00, 77.5),
      (12, 2710623, 30.00, 85),
    ],
  ),
  // the amended row: the dough's pie bakes 25 + 30 = 55 → 5005 35 %
  (
    '0986-strawberry-rhubarb-pie.yaml',
    5052.09,
    4968.00,
    646.53,
    51.02,
    [(5, 2710704, 56.00, 35)],
  ),
];

/// The record's ethanol kcal per 100 g by hand: energy less 4/9/4 of its
/// protein, fat and carbohydrate as cached (design §1.1 (A)).
double _ethanolByHand(FdcFood f) {
  final n = f.nutrientsPer100g;
  return n['208']! -
      4 * (n['203'] ?? 0) -
      9 * (n['204'] ?? 0) -
      4 * (n['205'] ?? 0);
}

/// A raw FDC detail's nutrient [number] (test/fixtures/fdc_raw, the live
/// M53 answers copied JSON-equal from .claude/diag/2026-10-07/live47_raw).
double _raw(Map<String, dynamic> food, String number) =>
    ((food['foodNutrients'] as List).cast<Map<String, dynamic>>().firstWhere(
              (n) => (n['nutrient'] as Map)['number'] == number,
            )['amount']
            as num)
        .toDouble();

void main() {
  test('the matcher version carries the batch (update the literal with a '
      'bump)', () {
    expect(matcherVersion, 53);
  });

  test('the energy split on the raw FDC details (§1.1 (A), P-E): ethanol '
      'kcal = energy less Atwater of protein, fat and carbohydrate — '
      '6.82–7.01 kcal per g of the measured ethanol (221), never 208 − 7 × '
      '221, which leaves a spirit negative', () {
    Map<String, dynamic> raw(int id) =>
        jsonDecode(File('test/fixtures/fdc_raw/$id.json').readAsStringSync())
            as Map<String, dynamic>;
    FdcFood cached(Map<String, dynamic> r) => FdcFood(
      fdcId: r['fdcId'] as int,
      description: r['description'] as String,
      dataType: r['dataType'] as String,
      nutrientsPer100g: {
        for (final n in const ['208', '203', '204', '205']) n: _raw(r, n),
      },
      portions: const [],
    );
    for (final (id, ethanol) in const [
      (2710689, 71.32), // Wine, white: 82 − 4 × 0.07 − 4 × 2.6
      (2710699, 231.00), // Brandy: 231, no protein, fat or carbohydrate
      (2710692, 104.40), // Wine, dessert, sweet: 160 − 4 × 0.2 − 4 × 13.7
      (175112, 104.52), // SR wine, dessert, dry
      (174835, 72.48), // SR Pinot Noir
      (173200, 64.76), // SR Riesling
    ]) {
      final r = raw(id);
      final e = ethanolKcalPer100g(cached(r));
      expect(e, closeTo(ethanol, 0.005), reason: '$id');
      expect(e / _raw(r, '221'), inInclusiveRange(6.80, 7.05), reason: '$id');
      expect(_raw(r, '208') - 7 * _raw(r, '221') < 0, id == 2710699);
    }
    // The SR records print their own factors (3.36 / 8.37 / 3.92): with
    // 6.93 × 221 they reproduce 208 to ±1 (critic 14).
    for (final id in const [175112, 174835, 173200]) {
      final r = raw(id);
      final f = (r['nutrientConversionFactors'] as List)
          .cast<Map<String, dynamic>>()
          .firstWhere((c) => c.containsKey('proteinValue'));
      final atwater =
          (f['proteinValue'] as num) * _raw(r, '203') +
          (f['fatValue'] as num) * _raw(r, '204') +
          (f['carbohydrateValue'] as num) * _raw(r, '205') +
          6.93 * _raw(r, '221');
      expect(atwater, closeTo(_raw(r, '208'), 1), reason: '$id');
    }
  });

  group('Q25 (v54)', skip: skipIfNoCorpus, () {
    late Directory tempDir;
    late SaltDatabase db;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('salt-v54-');
      final config = ServerConfig(
        dataDir: tempDir.path,
        logLevel: Level.WARNING,
        trustProxy: false,
      );
      db = SaltDatabase.open(config.dbPath)
        ..upsertSource(slug: _source, name: 'ATK', type: 'epub');
    });

    tearDown(() {
      db.dispose();
      tempDir.deleteSync(recursive: true);
    });

    /// [file] stored (its sections with it); its stored recipe.
    Recipe stored(String file) {
      final host = loadCorpusRecipe(file);
      db.upsertRecipe(host, sourceSlug: _source, contentHash: host.id);
      return db.recipeByIdOrSlug(host.id)!.recipe;
    }

    test('THE GATE: each of the 255 alcohol lines reads its kept %, its USDA '
        'code(s) and its flag (the minutes and the shape it prints)', () {
      final hosts = <String, Recipe>{};
      var reduced = 0;
      for (final (file, section, position, raw, fdcId, kept, code, flag)
          in _gate) {
        final host = hosts[file] ??= stored(file);
        final recipe = section == null
            ? host
            : nutritionRecipeOf(db, sectionKeyOf(host.id, section))!.recipe;
        final reason = '$file|$section|$position';
        expect(nutritionLines(recipe)[position].raw, raw, reason: reason);
        expect(alcoholRecords, contains(fdcId), reason: reason);
        final reading = alcoholReadingOf(recipe, position, fdcId);
        expect(reading.kept.toStringAsFixed(2), kept, reason: reason);
        expect(reading.code, code, reason: reason);
        expect(reading.flag, flag, reason: reason);
        if (reading.kept < 100) {
          reduced++;
        }
      }
      expect(_gate, hasLength(255));
      expect(reduced, 220);
    });

    Future<Recipe> computed(String file, FixtureProvider provider) async {
      final recipe = stored(file);
      for (final key in sectionChildKeysOf(db, recipe, ResolverMemo(db))) {
        expect(
          await matchAndCompute(
            db,
            provider,
            nutritionRecipeOf(db, key)!.recipe,
          ),
          isNull,
        );
      }
      expect(await matchAndCompute(db, provider, recipe), isNull);
      return db.recipeByIdOrSlug(recipe.id)!.recipe;
    }

    IngredientMatchRow rowOf(Recipe r, int position) => db
        .ingredientMatchesFor(r.id)
        .singleWhere((m) => m.position == position);

    double energyOf(Recipe r) =>
        ((jsonDecode(db.nutritionFor(r.id)!.totalsJson!) as Map)['energy']
                as num)
            .toDouble();

    test('energy only: each whole recipe moves its energy by exactly the '
        'ethanol its alcohol rows lose (by hand from the cached record) — '
        'record, grams, status and every other nutrient as on the v53 '
        'tree', () async {
      for (final (file, before, after, carbs, protein, rows) in _whole) {
        final recipe = await computed(
          file,
          FixtureProvider(pending: pendingSearches),
        );
        final lines = nutritionLines(recipe);
        var removed = 0.0;
        for (final (position, fdcId, grams, kept) in rows) {
          final row = rowOf(recipe, position);
          final reason = '$file|$position';
          expect(row.fdcId, fdcId, reason: reason);
          expect(row.status, 'auto', reason: reason);
          expect(row.hold, isNull, reason: reason);
          expect(row.grams!.toStringAsFixed(2), grams.toStringAsFixed(2));
          final retention = alcoholRetentionOf(recipe, lines[position], row);
          expect(retention!.kept, closeTo(kept, 1e-9), reason: reason);
          expect(
            compositeFlagOf(db, recipe, lines[position], row, ResolverMemo(db)),
            retention.flag,
            reason: reason,
          );
          removed +=
              _ethanolByHand(knownFood(db, fdcId)!) *
              row.grams! /
              100 *
              (1 - kept / 100);
        }
        final totals =
            jsonDecode(db.nutritionFor(recipe.id)!.totalsJson!)
                as Map<String, dynamic>;
        expect(energyOf(recipe), closeTo(after, 0.005), reason: file);
        expect(before - after, closeTo(removed, 0.011), reason: file);
        if (carbs > 0) {
          expect((totals['carbs'] as num).toDouble(), closeTo(carbs, 0.005));
          expect(
            (totals['protein'] as num).toDouble(),
            closeTo(protein, 0.005),
          );
        }
      }
    });

    test('a held row keeps its whole energy out (not counted, never '
        "reduced); a person's typed grams count and ARE reduced — the "
        'grams stay what was typed (P35, critic 12; the 59.00 g a '
        'DISCLOSED synthesized person input: the ¼ cup at the record’s '
        '236 g a cup); a Confirm keeps the flag', () async {
      final provider = FixtureProvider(pending: pendingSearches);
      final mahogany = await computed(
        '0129-mahogany-chicken-thighs.yaml',
        provider,
      );
      final line = nutritionLines(mahogany)[2];
      expect(rowOf(mahogany, 2).hold, 'partial_pour_away');
      expect(alcoholRetentionOf(mahogany, line, rowOf(mahogany, 2)), isNull);
      expect(
        compositeFlagOf(
          db,
          mahogany,
          line,
          rowOf(mahogany, 2),
          ResolverMemo(db),
        ),
        isNull,
      );
      // 5 + 30 + 20 (the low end) + the strained liquid's 1-min sauce = 56
      expect(
        alcoholReadingOf(mahogany, 2, 175112).flag,
        'approximate (USDA retention: alcohol cooked 56 min keeps 35 %)',
      );
      final held = energyOf(mahogany);
      await applyMatchOverride(db, provider, mahogany, 2, {
        'raw': line.raw,
        'grams': 59.0,
      });
      final typed = rowOf(mahogany, 2);
      expect(typed.grams, 59.0);
      expect(alcoholRetentionOf(mahogany, line, typed)!.kept, 35);
      final sherry = knownFood(db, 175112)!;
      expect(
        energyOf(mahogany) - held,
        closeTo(
          59.0 * sherry.nutrientsPer100g['208']! / 100 -
              59.0 * _ethanolByHand(sherry) / 100 * 0.65,
          0.005,
        ),
      );
      expect(energyOf(mahogany) - held, closeTo(49.60, 0.005));
      // A Confirm of the stew's wine keeps its flag and its energy.
      final stew = await computed('0005-best-beef-stew.yaml', provider);
      final before = energyOf(stew);
      await applyMatchOverride(db, provider, stew, 8, {
        'raw': nutritionLines(stew)[8].raw,
        'confirmed': true,
      });
      expect(rowOf(stew, 8).status, 'confirmed');
      expect(
        compositeFlagOf(
          db,
          stew,
          nutritionLines(stew)[8],
          rowOf(stew, 8),
          ResolverMemo(db),
        ),
        "approximate (USDA retention: alcohol cooked 155 min keeps 5 %, the table's 2½-hour figure)",
      );
      expect(energyOf(stew), closeTo(before, 0.005));
    });

    test('two lines of one head each read their own use — the memo keyed by '
        'the line (critic 10): crepes-suzette |6 the batter (sub-minute), |8 '
        'the flambé split, read in either order and with the memo off', () {
      final orders = [
        [6, 8],
        [8, 6],
      ];
      final readings = <List<String?>>[];
      for (final memoOff in [false, true]) {
        memoOffForTest = memoOff;
        try {
          for (final order in orders) {
            final crepes = loadCorpusRecipe('0960-crepes-suzette.yaml');
            final got = {
              for (final p in order) p: alcoholReadingOf(crepes, p, 2710699),
            };
            readings.add([got[6]!.flag, got[8]!.flag]);
            expect(got[6]!.kept, 85);
            expect(got[8]!.kept, 77.5);
          }
        } finally {
          memoOffForTest = false;
        }
      }
      expect(readings.map((r) => r.join(' | ')).toSet(), hasLength(1));
      expect(readings.first, [
        'approximate (USDA retention: alcohol stirred into hot liquid keeps 85 %)',
        'approximate (USDA retention: 3 tablespoons flamed keeps 75 %; 1 tablespoon stirred into hot liquid keeps 85 %)',
      ]);
    });
  });
}
