import 'package:dart_frog/dart_frog.dart';
import 'package:salt_server/src/db/salt_database.dart';
import 'package:salt_server/src/handlers/auth_handlers.dart';
import 'package:salt_server/src/handlers/user_handlers.dart';
import 'package:salt_server/src/http/method_guard.dart';
import 'package:salt_server/src/middleware/auth.dart';

/// `GET /api/v1/users` (admin) — list accounts.
/// `POST /api/v1/users` (admin) `{username, role}` — create an account with
/// an autogenerated temporary password (returned once).
Future<Response> onRequest(RequestContext context) async {
  requireMethods(context, {HttpMethod.get, HttpMethod.post});
  final actor = requireAdmin(context);
  final db = context.read<SaltDatabase>();

  if (context.request.method == HttpMethod.get) {
    return Response.json(body: listUsersHandler(db, actor));
  }

  requireCsrf(context, actor);
  final body = await readJsonBody(context.request.json);
  return Response.json(
    body: await createUserHandler(
      db,
      context.read<AuthRuntime>().hasher,
      actor,
      username: requireStringField(body, 'username'),
      role: requireStringField(body, 'role'),
    ),
  );
}
