#!/usr/bin/env python3
"""Regenerates lib/core/widgets/lucide_catalog.g.dart from the forui_assets
package (forui's own Lucide set): every icon's canonical kebab-case name (the
form the server stores in tag styles) mapped to its FLucideIcons glyph.

Reads forui_assets rather than lucide_icons_flutter so the app ships ONE icon
font (forui's), not two — see feedback-forui-icons."""
import re, glob, os, pathlib, subprocess

cache = os.path.expanduser('~/.pub-cache/hosted/pub.dev')
src_candidates = sorted(glob.glob(f'{cache}/forui_assets-*/lib/src/assets.g.dart'))
src = open(src_candidates[-1]).read()

# forui_assets lists each icon as a doc comment carrying its kebab name in
# backticks, immediately followed by the camelCase constant, e.g.:
#   /// [![`chef-hat`](.../chef-hat.svg)](https://lucide.dev/icons/chef-hat)
#   static const chefHat = IconData(58028, fontFamily: 'ForuiLucideIcons', ...);
pattern = re.compile(
    r'/// \[!\[`(?P<kebab>[a-z0-9][a-z0-9-]*)`\][^\n]*\n'
    r'  static const (?P<name>[a-zA-Z0-9]+) = IconData\(',
)
entries = [(m.group('kebab'), m.group('name')) for m in pattern.finditer(src)]

seen = set()
unique = [(k, n) for k, n in entries if not (k in seen or seen.add(k))]
out = pathlib.Path(__file__).parent.parent / 'lib/core/widgets/lucide_catalog.g.dart'
with open(out, 'w') as f:
    f.write("// GENERATED by tool/gen_lucide_catalog.py — do not edit by hand.\n")
    f.write("// Maps every Lucide icon's canonical kebab-case name (the form the\n")
    f.write("// server stores in tag styles) to its forui glyph.\n\n")
    f.write("import 'package:flutter/widgets.dart';\n")
    f.write("import 'package:forui/forui.dart';\n\n")
    f.write("/// Every Lucide icon by canonical name (forui's FLucideIcons set).\n")
    f.write("const Map<String, IconData> lucideIconsByName = {\n")
    for kebab, name in unique:
        f.write(f"  '{kebab}': FLucideIcons.{name},\n")
    f.write("};\n")

# Emit it already formatted, so regenerating never un-formats the tree (this
# file is checked in, and `dart format` would otherwise rewrite it every time).
subprocess.run(['dart', 'format', str(out)], check=True, capture_output=True)
print(f'{len(unique)} icons -> {out}')
