#!/usr/bin/env python3
"""Regenerates lib/core/widgets/lucide_catalog.g.dart from the
lucide_icons_flutter package: every icon's canonical kebab-case name (the
form the server stores in tag styles) mapped to its IconData constant."""
import re, subprocess, sys, pathlib

pkg = subprocess.run(
    ['dart', 'pub', 'deps', '--json'], capture_output=True, text=True,
    cwd=pathlib.Path(__file__).parent.parent)
import json, glob, os
cache = os.path.expanduser('~/.pub-cache/hosted/pub.dev')
src_candidates = sorted(glob.glob(f'{cache}/lucide_icons_flutter-*/lib/lucide_icons.dart'))
src = open(src_candidates[-1]).read()

entries = []
pattern = re.compile(
    r'/// (?P<kebab>[a-z0-9][a-z0-9-]*)\n(?:  /// .*\n)*?'
    r'  static const IconData (?P<name>[a-zA-Z0-9]+) = const IconData\(',
)
for match in pattern.finditer(src):
    name = match.group('name')
    if name.endswith('Dir') or name.endswith('100'):
        continue
    entries.append((match.group('kebab'), name))

seen = set()
unique = [(k, n) for k, n in entries if not (k in seen or seen.add(k))]
out = pathlib.Path(__file__).parent.parent / 'lib/core/widgets/lucide_catalog.g.dart'
with open(out, 'w') as f:
    f.write("// GENERATED by tool/gen_lucide_catalog.py — do not edit by hand.\n")
    f.write("// Maps every Lucide icon's canonical kebab-case name (the form the\n")
    f.write("// server stores in tag styles) to its glyph.\n\n")
    f.write("import 'package:flutter/widgets.dart';\n")
    f.write("import 'package:lucide_icons_flutter/lucide_icons.dart';\n\n")
    f.write("/// Every Lucide icon by canonical name.\n")
    f.write("const Map<String, IconData> lucideIconsByName = {\n")
    for kebab, name in unique:
        f.write(f"  '{kebab}': LucideIcons.{name},\n")
    f.write("};\n")
print(f'{len(unique)} icons -> {out}')
