import 'dart:math';

import 'package:logging/logging.dart';
import 'package:salt_server/src/auth/password_hasher.dart';
import 'package:salt_server/src/db/salt_database.dart';
import 'package:salt_server/src/exceptions.dart';
import 'package:salt_server/src/handlers/auth_handlers.dart' show auditLog;
import 'package:salt_server/src/http/timestamps.dart';
import 'package:salt_server/src/middleware/auth.dart';
import 'package:sqlite3/sqlite3.dart';

/// Account-administration events share the `auth` audit channel (see
/// [auditLog]) so one filter in the admin log viewer shows sign-ins and
/// account changes together. `PATCH /users/7 -> 200` in the access log names
/// neither the acting admin nor what changed; these lines carry both. The
/// generated temporary password is a secret and never appears.
///
/// Via [auditLog], not `Logger('auth')` directly: the shared instance is where
/// the level pin that survives `LOG_LEVEL=WARN` lives, and naming the logger
/// here instead would depend on some other file having been touched first.
final Logger _log = auditLog;

/// Unambiguous alphabet for autogenerated temporary passwords (no I/L/O/0/1
/// look-alikes; mixed case + digits).
const String _tempPasswordAlphabet =
    'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';

final RegExp _usernamePattern = RegExp(r'^[a-z0-9_.-]{3,32}$');

final Random _random = Random.secure();

/// A 20-character CSPRNG temporary password. Shown to the admin exactly
/// once; the account is created with `must_change_password`.
String generateTempPassword() => List.generate(
  20,
  (_) => _tempPasswordAlphabet[_random.nextInt(_tempPasswordAlphabet.length)],
).join();

Map<String, Object?> _userJson(UserRow user) => {
  'id': user.id,
  'username': user.username,
  'role': user.role,
  'disabled': user.disabled,
  'must_change_password': user.mustChangePassword,
  'created_at': isoUtc(user.createdAt),
  'last_active_at': isoUtc(user.lastActiveAt),
};

/// `GET /api/v1/users` (admin) — every account.
Map<String, Object?> listUsersHandler(SaltDatabase db, AuthUser actor) => {
  'items': [for (final user in db.listUsers()) _userJson(user)],
};

/// `POST /api/v1/users` (admin) `{username, role}` — creates a member/admin
/// with an autogenerated temporary password (returned once, never logged)
/// and `must_change_password` set.
Future<Map<String, Object?>> createUserHandler(
  SaltDatabase db,
  PasswordHasher hasher,
  AuthUser actor, {
  required String username,
  required String role,
}) async {
  final normalized = username.trim().toLowerCase();
  if (!_usernamePattern.hasMatch(normalized)) {
    throw const ValidationException(
      'Username must be 3-32 characters: letters, digits, underscore, '
      'dot, or dash.',
    );
  }
  if (role != 'admin' && role != 'member') {
    throw const ValidationException("Role must be 'admin' or 'member'.");
  }
  final tempPassword = generateTempPassword();
  final passwordHash = await hasher.hash(tempPassword);
  final int id;
  try {
    id = db.createUser(
      username: normalized,
      passwordHash: passwordHash,
      role: role,
      mustChangePassword: true,
    );
  } on SqliteException {
    throw ConflictException('The username "$normalized" is already taken.');
  }
  _log.info(
    'User created: $normalized (id $id, $role) by ${actor.username} '
    '(id ${actor.id}).',
  );
  return {
    'user': _userJson(db.userById(id)!),
    'temp_password': tempPassword,
  };
}

/// `PATCH /api/v1/users/<id>` (admin) `{role? | disabled?}`. Admins cannot
/// change their own role or disable themselves (so the last admin cannot
/// lock the server).
Map<String, Object?> patchUserHandler(
  SaltDatabase db,
  AuthUser actor,
  int userId, {
  String? role,
  bool? disabled,
}) {
  final user = db.userById(userId);
  if (user == null) {
    throw NotFoundException('user not found: $userId');
  }
  if (role != null) {
    if (role != 'admin' && role != 'member') {
      throw const ValidationException("Role must be 'admin' or 'member'.");
    }
    if (userId == actor.id) {
      throw const ValidationException('You cannot change your own role.');
    }
    db.setUserRole(userId, role);
    _log.info(
      'Role changed: ${user.username} (id $userId) is now $role, by '
      '${actor.username} (id ${actor.id}).',
    );
  }
  if (disabled != null) {
    if (userId == actor.id) {
      throw const ValidationException('You cannot disable your own account.');
    }
    db.setUserDisabled(userId, disabled: disabled);
    _log.info(
      'Account ${disabled ? 'disabled' : 'enabled'}: ${user.username} '
      '(id $userId) by ${actor.username} (id ${actor.id}).',
    );
  }
  return {'user': _userJson(db.userById(userId)!)};
}

/// `DELETE /api/v1/users/<id>` (admin) — permanently removes the account and
/// everything keyed to it (sessions, API tokens, favorites, and personal notes
/// cascade; recipes are not user-owned, so they survive). Admins cannot delete
/// themselves, which keeps at least the acting admin in place — the same guard
/// that stops the last admin locking the server (see [patchUserHandler]).
Map<String, Object?> deleteUserHandler(
  SaltDatabase db,
  AuthUser actor,
  int userId,
) {
  if (userId == actor.id) {
    throw const ValidationException('You cannot delete your own account.');
  }
  // Read the row before the delete purely so the log can name who was
  // removed; a missing row still fails closed with the same 404.
  final target = db.userById(userId);
  if (target == null || !db.deleteUser(userId)) {
    throw NotFoundException('user not found: $userId');
  }
  _log.warning(
    'User deleted: ${target.username} (id $userId) by ${actor.username} '
    '(id ${actor.id}).',
  );
  return {'ok': true};
}

/// `POST /api/v1/users/<id>/reset_password` (admin) — new temporary
/// password (returned once), forces a change at next sign-in, and signs the
/// user out everywhere: every session AND every personal access token.
///
/// The tokens matter as much as the sessions, and used not to go. A PAT is its
/// own credential: dropping the sessions left it alive, `must_change_password`
/// only FROZE it (403), and the moment the user completed the forced change it
/// returned to full service — so the action an operator reaches for first on a
/// suspected compromise was the one path that evicted everything except the
/// attacker. `recoverAdmin` already reasoned this out for the neighbouring
/// flow; this now matches it.
///
/// The cost is real and accepted (user's call, 2026-07-16): a routine reset
/// also kills that user's own scripts, and there is no reset that spares them.
/// The count comes back in the response so the admin can see what went.
Future<Map<String, Object?>> resetPasswordHandler(
  SaltDatabase db,
  PasswordHasher hasher,
  AuthUser actor,
  int userId,
) async {
  if (userId == actor.id) {
    // Resetting yourself would delete your current session mid-request and
    // force a change you could have made directly — use change password.
    throw const ValidationException(
      'Use "Change password" for your own account.',
    );
  }
  final user = db.userById(userId);
  if (user == null) {
    throw NotFoundException('user not found: $userId');
  }
  final tempPassword = generateTempPassword();
  final passwordHash = await hasher.hash(tempPassword);
  // Eviction and rotation are ONE transaction (`updatePasswordHash` runs the
  // revocation inside its own), so no partial failure can land on "password
  // changed, tokens alive" — the compromise this reset exists to end. Same
  // guarantee on `changePassword` and `recoverAdmin`.
  final revokedTokens = db.updatePasswordHash(
    userId,
    passwordHash,
    mustChangePassword: true,
    revokeApiTokens: true,
  );
  // WARNING, not INFO: this is the action an operator takes when an account
  // is in doubt, so it should stand out in the viewer's default filter.
  _log.warning(
    'Password reset: ${user.username} (id $userId) by ${actor.username} '
    '(id ${actor.id}); sessions dropped, $revokedTokens API token(s) '
    'revoked.',
  );
  return {
    'user': _userJson(db.userById(userId)!),
    'temp_password': tempPassword,
    'revoked_tokens': revokedTokens,
  };
}
