import 'dart:math';

import 'package:salt_server/src/auth/password_hasher.dart';
import 'package:salt_server/src/db/salt_database.dart';
import 'package:salt_server/src/exceptions.dart';
import 'package:salt_server/src/http/timestamps.dart';
import 'package:salt_server/src/middleware/auth.dart';
import 'package:sqlite3/sqlite3.dart';

/// Unambiguous alphabet for autogenerated temporary passwords (no I/L/O/0/1
/// look-alikes; mixed case + digits).
const String _tempPasswordAlphabet =
    'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';

final RegExp _usernamePattern = RegExp(r'^[a-z0-9_.-]{3,32}$');

final Random _random = Random.secure();

/// A 20-character CSPRNG temporary password. Shown to the admin exactly
/// once; the account is created with `must_change_password`.
String generateTempPassword() => List.generate(
      20,
      (_) =>
          _tempPasswordAlphabet[_random.nextInt(_tempPasswordAlphabet.length)],
    ).join();

Map<String, Object?> _userJson(UserRow user) => {
      'id': user.id,
      'username': user.username,
      'role': user.role,
      'disabled': user.disabled,
      'must_change_password': user.mustChangePassword,
      'created_at': isoUtc(user.createdAt),
      'last_active_at': isoUtc(user.lastActiveAt),
    };

/// `GET /api/v1/users` (admin) — every account.
Map<String, Object?> listUsersHandler(SaltDatabase db, AuthUser actor) => {
      'items': [for (final user in db.listUsers()) _userJson(user)],
    };

/// `POST /api/v1/users` (admin) `{username, role}` — creates a member/admin
/// with an autogenerated temporary password (returned once, never logged)
/// and `must_change_password` set.
Future<Map<String, Object?>> createUserHandler(
  SaltDatabase db,
  PasswordHasher hasher,
  AuthUser actor, {
  required String username,
  required String role,
}) async {
  final normalized = username.trim().toLowerCase();
  if (!_usernamePattern.hasMatch(normalized)) {
    throw const ValidationException(
      'Username must be 3-32 characters: letters, digits, underscore, '
      'dot, or dash.',
    );
  }
  if (role != 'admin' && role != 'member') {
    throw const ValidationException("Role must be 'admin' or 'member'.");
  }
  final tempPassword = generateTempPassword();
  final passwordHash = await hasher.hash(tempPassword);
  final int id;
  try {
    id = db.createUser(
      username: normalized,
      passwordHash: passwordHash,
      role: role,
      mustChangePassword: true,
    );
  } on SqliteException {
    throw ConflictException('The username "$normalized" is already taken.');
  }
  return {
    'user': _userJson(db.userById(id)!),
    'temp_password': tempPassword,
  };
}

/// `PATCH /api/v1/users/<id>` (admin) `{role? | disabled?}`. Admins cannot
/// change their own role or disable themselves (so the last admin cannot
/// lock the server).
Map<String, Object?> patchUserHandler(
  SaltDatabase db,
  AuthUser actor,
  int userId, {
  String? role,
  bool? disabled,
}) {
  final user = db.userById(userId);
  if (user == null) {
    throw NotFoundException('user not found: $userId');
  }
  if (role != null) {
    if (role != 'admin' && role != 'member') {
      throw const ValidationException("Role must be 'admin' or 'member'.");
    }
    if (userId == actor.id) {
      throw const ValidationException('You cannot change your own role.');
    }
    db.setUserRole(userId, role);
  }
  if (disabled != null) {
    if (userId == actor.id) {
      throw const ValidationException('You cannot disable your own account.');
    }
    db.setUserDisabled(userId, disabled: disabled);
  }
  return {'user': _userJson(db.userById(userId)!)};
}

/// `POST /api/v1/users/<id>/reset_password` (admin) — new temporary
/// password (returned once), forces a change at next sign-in, and signs the
/// user out everywhere.
Future<Map<String, Object?>> resetPasswordHandler(
  SaltDatabase db,
  PasswordHasher hasher,
  AuthUser actor,
  int userId,
) async {
  if (userId == actor.id) {
    // Resetting yourself would delete your current session mid-request and
    // force a change you could have made directly — use change password.
    throw const ValidationException(
      'Use "Change password" for your own account.',
    );
  }
  final user = db.userById(userId);
  if (user == null) {
    throw NotFoundException('user not found: $userId');
  }
  final tempPassword = generateTempPassword();
  db.updatePasswordHash(
    userId,
    await hasher.hash(tempPassword),
    mustChangePassword: true,
  );
  return {
    'user': _userJson(db.userById(userId)!),
    'temp_password': tempPassword,
  };
}
